/* ModelQuest v6 — explanation layer: analogy -> real meaning -> consequence -> technical depth. */
(()=>{
const E={
'linear regression':{title:'Linear Regression',analogy:'Imagine calibrating a spring scale. You hang known weights on it, notice how far the spring stretches, and draw one straight line that best follows those measurements.',plain:'Linear regression does the same kind of job with numbers. It learns a straight-line relationship between one or more inputs and a numeric output. In our force-sensor quest, known reference loads are paired with sensor voltage. The model learns how much force usually changes when voltage changes, then uses that relationship to estimate an unknown force.',why:'Use it when the output is a number and a roughly straight-line relationship is a sensible starting point. It is also an excellent baseline because you can inspect exactly what it learned.',technical:'For one input, the model is ŷ = wx + b. Training chooses w and b to minimize a loss, commonly squared error. With several inputs, the same idea becomes ŷ = w₁x₁ + w₂x₂ + … + b.',small:'If voltage goes up in a predictable way as force increases, learn that relationship and use it to estimate force later.'},
'gradient descent':{title:'Gradient Descent',analogy:'Picture standing on a mountain in thick fog. You cannot see the whole landscape, but you can feel which direction slopes downward. Take a small step downhill, check the slope again, and repeat until you reach a low point.',plain:'Gradient descent is a way of improving model parameters little by little. The model first makes predictions and calculates how wrong they are. Then it measures which direction each parameter should move to reduce that error. In our calibration line, those parameters can be the slope and intercept. Each training step nudges them toward values that fit the measurements better.',why:'It matters because large neural networks have far too many parameters to solve by hand. Gradient-based optimization gives us a repeatable way to improve millions or billions of values.',technical:'If θ is a parameter and L is the loss, an update is θ ← θ − η∂L/∂θ. η is the learning rate. The derivative tells us the local direction and sensitivity of the loss.',small:'Predict → see how wrong → move the model a little in a better direction → repeat.'},
'learning rate':{title:'Learning Rate',analogy:'If you are walking downhill in fog, tiny steps are safe but slow. Giant jumps may cross the valley and send you up the other side.',plain:'The learning rate controls how large each optimization update is. It does not tell the model what the correct answer is; it controls how aggressively the model reacts to the gradient. A rate that is too small can make useful learning painfully slow. A rate that is too large can make loss bounce around, explode, or never settle.',why:'When training behaves strangely, learning rate is one of the first knobs worth checking. It changes training behavior without changing the dataset or model architecture.',technical:'The learning rate η multiplies the gradient in the parameter update. Modern optimizers such as Adam adapt effective step sizes per parameter, but the base learning rate still matters greatly.',small:'It is the size of each correction step.'},
'feature':{title:'Feature',analogy:'If a mechanic is diagnosing a bearing, vibration, temperature, RPM, and hours of use are clues. Each clue is a feature.',plain:'A feature is one piece of information the model is allowed to use when making a prediction. Good features contain useful signal available at the moment you actually need the prediction. A column can exist in your dataset and still be a bad feature—for example a repair flag that is only created after the failure already happened.',why:'Models cannot reason from information they never receive. Feature choice often matters as much as model choice.',technical:'Features are the columns or dimensions in X. Numerical, categorical, text, image, audio, and time-series data all become model-readable features through suitable representations or preprocessing.',small:'A feature is a clue the model gets to look at.'},
'target':{title:'Target / Label',analogy:'When studying old machine records, the sensor readings are the clues; whether the bearing actually failed is the answer written on the back of the card.',plain:'The target is the answer we want a supervised model to learn to predict. For regression it is a number, such as force or remaining life. For classification it is a category, such as normal/failure. During training we show the model both the clues and the known answer so it can measure its mistakes.',why:'If the target is poorly defined or incorrectly labeled, the model can learn the wrong job perfectly.',technical:'Targets are commonly stored as y. Regression targets are often continuous; classification labels may be encoded as integers or one-hot vectors depending on the framework.',small:'The target is the answer we want the model to learn.'},
'loss':{title:'Loss',analogy:'Think of loss as a scoreboard where lower is better. Every wrong prediction adds penalty points. Training tries to make the scoreboard shrink.',plain:'Loss converts model mistakes into one number that the optimizer can work with. The exact loss depends on the task. Squared error heavily penalizes large regression mistakes; cross-entropy is common for classification. A model does not directly understand “this prediction is bad.” The loss function defines mathematically what bad means.',why:'Changing the loss changes what the model is rewarded for improving, so it can change the behavior of training.',technical:'A loss function L(y,ŷ) maps targets and predictions to a scalar. Gradients of that scalar with respect to parameters are what backpropagation and optimizers use.',small:'Loss is the number training tries to make smaller.'},
'mae':{title:'MAE — Mean Absolute Error',analogy:'If a force sensor is off by 2 N, 5 N, and 8 N on three tests, MAE asks: “On an average test, how many newtons are we off?”',plain:'MAE measures the average absolute distance between predictions and real values. Because it ignores whether the error was above or below, positive and negative mistakes cannot cancel each other out. It is easy to explain because the result stays in the same unit as the target.',why:'Use it when you want an intuitive typical error size and do not want very large errors to dominate as strongly as they do with squared error.',technical:'MAE = (1/n)Σ|yᵢ−ŷᵢ|. It is less sensitive to outliers than MSE but has a non-smooth point at zero error.',small:'Average size of the mistake, in the same unit as the answer.'},
'mse':{title:'MSE — Mean Squared Error',analogy:'Imagine charging a much bigger penalty for a calibration miss of 20 N than for four misses of 5 N. Squaring the error makes large mistakes hurt disproportionately.',plain:'MSE squares every prediction error before averaging. That makes large errors much more influential than small ones. This is useful when large misses are especially undesirable, and it also gives linear regression convenient mathematical properties.',why:'It is common in optimization, but its numerical value is in squared units, so it is less intuitive to explain directly than MAE.',technical:'MSE = (1/n)Σ(yᵢ−ŷᵢ)². For ordinary least squares, minimizing the sum of squared residuals gives the familiar best-fit linear solution.',small:'Big mistakes get punished much more than small mistakes.'},
'r²':{title:'R² — Coefficient of Determination',analogy:'Suppose you could ignore the sensor completely and always guess the average force. R² asks how much better your fitted relationship explains the measurements compared with that boring average guess.',plain:'An R² near 1 means the model explains a large share of the variation in the observed target values. Around 0 means the model is doing roughly no better than predicting the average on that data. It can even become negative on test data when predictions are worse than the average baseline.',why:'R² is useful for understanding fit, but it does not tell you whether errors are small enough for the engineering requirement, whether the relationship is causal, or whether the model will survive a new operating condition.',technical:'R² = 1 − SS_res/SS_tot, where SS_res is residual sum of squares and SS_tot is total variation around the target mean.',small:'It compares your model with simply guessing the average.'},
'outlier':{title:'Outlier',analogy:'If five calibration weights produce sensible readings and one suddenly says 10× more voltage, that point is like one witness telling a very different story from everyone else.',plain:'An outlier is an observation unusually far from the main pattern. It might be a sensor glitch, unit conversion mistake, data-entry error, unusual operating state, or a genuine rare event. The important habit is not “delete outliers.” It is “investigate why this point is different.”',why:'Some models, including ordinary least-squares regression, can be pulled strongly by extreme observations. But deleting a real rare failure could remove exactly the behavior you need the model to learn.',technical:'Outlier handling can involve domain checks, robust statistics, transformations, robust regression, winsorization, isolation methods, or simply retaining the point after verification.',small:'A point that behaves very differently from most of the data.'},
'overfitting':{title:'Overfitting',analogy:'Imagine memorizing the exact answers to last year’s exam instead of learning the subject. You score perfectly on the old paper and struggle on a new one.',plain:'Overfitting happens when a model becomes too specialized to the training examples—including their noise and accidents—instead of learning a pattern that works on new data. Training performance keeps improving while validation or test performance stops improving or gets worse.',why:'Real ML is judged on unseen future cases, not on how beautifully it remembers the training set.',technical:'Overfitting is related to model capacity, sample size, noise, regularization, data leakage, and distribution shift. Common controls include simpler models, more representative data, L1/L2 penalties, dropout, augmentation, early stopping, and cross-validation.',small:'The model remembers the practice questions instead of learning the lesson.'},
'data leakage':{title:'Data Leakage',analogy:'It is like giving a student tomorrow’s answer sheet during practice, then being impressed by the test score.',plain:'Leakage happens when information that should be unavailable at prediction time sneaks into training, preprocessing, validation, or features. In predictive maintenance, a “repair completed” field could reveal that failure already happened. The frightening part is that leaked code often runs perfectly and produces unusually impressive metrics.',why:'Leakage creates confidence in a model that will collapse in the real world.',technical:'Leakage includes target leakage, train/test contamination, fitting preprocessing on all data, duplicate entities across splits, and time leakage. Pipelines and time-aware/entity-aware splitting help prevent it.',small:'The model secretly gets information from the future or from the answer.'},
'precision':{title:'Precision',analogy:'If your alarm says “bearing failure” 10 times and only 7 are real failures, precision asks how trustworthy the alarm is when it speaks up.',plain:'Precision measures the fraction of predicted positives that were actually positive. High precision means fewer false alarms. That can matter when inspections or shutdowns are expensive.',why:'Precision alone can be misleading: a model can become very precise by making only a few extremely cautious positive predictions and missing many real failures.',technical:'Precision = TP/(TP+FP). It trades off with recall as the classification threshold changes.',small:'When the model says YES, how often is it right?'},
'recall':{title:'Recall',analogy:'If 10 bearings truly fail and your system catches 9 of them, recall asks how many real failures you managed to catch.',plain:'Recall measures the fraction of actual positives detected by the model. High recall is important when missing a positive event is costly or dangerous, such as failure detection or safety screening.',why:'Maximizing recall alone can cause many false alarms, so the right operating point depends on real consequences.',technical:'Recall = TP/(TP+FN). Lowering a decision threshold often increases recall while reducing precision.',small:'Of all the real YES cases, how many did the model find?'},
'confusion matrix':{title:'Confusion Matrix',analogy:'Think of it as a four-box inspection report: correctly caught failures, correctly cleared healthy machines, false alarms, and missed failures.',plain:'A confusion matrix shows exactly what kinds of classification decisions the model made. Accuracy compresses everything into one number; the matrix keeps the four outcomes separate so you can see which mistake is happening.',why:'Two models can have the same accuracy but very different safety or business consequences because one misses failures while the other raises more false alarms.',technical:'The four cells are true positive, true negative, false positive, and false negative. Precision, recall, specificity, and many other metrics are derived from them.',small:'Four boxes showing correct decisions and the two different kinds of mistakes.'},
'random forest':{title:'Random Forest',analogy:'Instead of asking one mechanic for a diagnosis, ask hundreds who each inspect slightly different evidence, then combine their votes.',plain:'A Random Forest trains many decision trees on varied samples and feature subsets. Each tree is intentionally a little different. For classification, the trees vote; for regression, their predictions are averaged. Combining many imperfect trees usually gives a more stable model than trusting one deep tree.',why:'Forests are strong practical baselines for tabular engineering data because they handle nonlinear relationships and interactions with relatively little preprocessing.',technical:'Random forests use bagging plus random feature selection. Key hyperparameters include n_estimators, max_depth, max_features, min_samples_leaf, and class_weight.',small:'Many different decision trees make a decision together.'},
'knn':{title:'K-Nearest Neighbors (KNN)',analogy:'If an unknown machine state looks most like five past examples, ask those five examples what they were and let them vote.',plain:'KNN stores the training examples rather than learning a compact equation. To predict a new example, it measures distance to known examples, finds the k closest ones, and uses their labels or values. The idea is simple, but the meaning of “close” depends heavily on feature scaling.',why:'KNN is excellent for understanding feature space and local similarity, but prediction can become expensive on large datasets.',technical:'Common choices include Euclidean or Minkowski distance, uniform versus distance-weighted voting, and k. Small k can be noisy; large k smooths local structure.',small:'Find the most similar old examples and ask them to vote.'},
'svm':{title:'Support Vector Machine (SVM)',analogy:'Imagine placing the widest possible safety corridor between two groups of parts instead of drawing a boundary that barely squeezes between them.',plain:'An SVM looks for a decision boundary that separates classes while maximizing the margin to important boundary examples. Those closest examples are the support vectors. With kernels, SVMs can create nonlinear boundaries without explicitly building every transformed feature.',why:'SVMs can work very well on small-to-medium, well-scaled datasets with clear structure.',technical:'Key controls include C, which balances margin width against classification errors, and kernel parameters such as gamma for the RBF kernel.',small:'Draw a boundary with as much breathing room between classes as possible.'},
'k-means':{title:'K-Means Clustering',analogy:'Drop k magnets onto a map of machine operating points. Every point attaches to its nearest magnet; then each magnet moves to the center of the points it attracted. Repeat.',plain:'K-Means groups unlabeled examples by repeatedly assigning points to the nearest centroid and moving each centroid to the average of its assigned points. It always creates exactly k groups, whether or not those groups have useful real-world meaning.',why:'It is useful for exploring operating modes or customer/machine segments, but interpretation still requires domain knowledge.',technical:'The objective minimizes within-cluster squared distance. Scaling matters because distance is sensitive to units. Initialization can affect the result, which is why multiple initializations are commonly used.',small:'Points join the nearest center, then the centers move, until things settle.'},
'pca':{title:'PCA — Principal Component Analysis',analogy:'Imagine a cloud of 3D points. Turn a camera until the 2D photograph preserves as much of the spread as possible. PCA finds useful viewing directions mathematically.',plain:'PCA creates new axes that capture decreasing amounts of variation in the data. It can reduce many correlated features into fewer components, making visualization, compression, or some downstream models easier.',why:'PCA can simplify high-dimensional data, but the new components are mixtures of original features and may be harder to interpret physically.',technical:'PCA finds orthogonal directions associated with the largest eigenvalues of the covariance structure, commonly computed using singular value decomposition.',small:'Rotate the data to find directions that keep the most information.'},
'neuron':{title:'Artificial Neuron',analogy:'Think of a small decision unit receiving several sensor readings. It turns each input knob up or down, adds them together, adds an offset, and passes the result through a gate.',plain:'A neuron takes inputs, multiplies each by a learned weight, adds a learned bias, then usually applies an activation function. One neuron is simple; networks become powerful by arranging many of these operations in layers.',why:'Understanding one neuron makes dense neural networks much less mysterious: they are large collections of repeated weighted calculations.',technical:'z = w·x + b, followed by activation a = f(z). During training, gradients adjust w and b.',small:'Weighted inputs + bias + activation = one neuron output.'},
'weight':{title:'Weight',analogy:'If vibration is a much stronger clue for failure than ambient temperature, the model can learn a larger “importance knob” for vibration.',plain:'A weight multiplies an input or intermediate signal. Its magnitude and sign determine how strongly that signal pushes the next calculation. Neural networks learn weights automatically from data rather than having a person assign them manually.',why:'Weights are the main learned memory of many neural networks.',technical:'Weights are trainable parameters optimized by gradients. Their individual values are rarely meaningful alone in deep models; behavior emerges from many weights working together.',small:'A learned multiplier that controls how strongly one signal matters.'},
'bias':{title:'Bias Parameter',analogy:'A thermostat may need a starting offset before sensor effects are considered. Bias gives a neuron or linear model that movable starting point.',plain:'A bias is a learned value added independently of the current input. Without it, many model components would be forced through zero and lose flexibility. In a regression line it is the intercept.',why:'Bias allows the model to shift its response instead of only changing steepness.',technical:'For a neuron z=w·x+b. b is optimized just like weights through backpropagation.',small:'A learned offset that shifts the model response.'},
'relu':{title:'ReLU Activation',analogy:'Think of a one-way gate: negative signals are blocked at zero while positive signals pass through unchanged.',plain:'ReLU introduces nonlinearity into neural networks. Without nonlinear activations between layers, stacking many dense layers would collapse into another linear transformation and could not learn complex curved boundaries.',why:'ReLU is simple, fast, and historically very effective for deep networks, though modern architectures may use GELU, SiLU, and others.',technical:'ReLU(x)=max(0,x). Its gradient is 1 for positive inputs and 0 for negative inputs, with a convention at zero.',small:'Negative becomes zero; positive passes through.'},
'backpropagation':{title:'Backpropagation',analogy:'If the final product is wrong, trace responsibility backward through the assembly line to see which earlier adjustments contributed to the mistake.',plain:'Backpropagation efficiently calculates how the final loss depends on every trainable parameter in a neural network. It starts from the loss and works backward through operations using the chain rule, producing gradients for weights and biases.',why:'Without backpropagation, training large multilayer networks would require impractically expensive parameter-by-parameter experimentation.',technical:'Reverse-mode automatic differentiation reuses intermediate derivatives through the computation graph. The optimizer then uses the resulting gradients to update parameters.',small:'Work backward from the mistake to learn which weights should change.'},
'transformer':{title:'Transformer',analogy:'When reading a maintenance sentence, each word can look around the whole sentence and decide which other words are important for understanding its meaning.',plain:'Transformers process sequences using attention rather than relying mainly on step-by-step recurrence. Tokens are converted to embeddings, attention mixes information between positions, and feed-forward layers transform those representations. Stacking many blocks creates powerful contextual representations.',why:'Transformers became the foundation of modern language models and are also widely used in vision, audio, and multimodal systems.',technical:'A standard block contains multi-head self-attention, feed-forward networks, residual connections, normalization, and positional information. Attention uses query, key, and value projections.',small:'Every token can selectively gather information from other tokens.'},
'attention':{title:'Self-Attention',analogy:'In “The pump stopped because it overheated,” the word “it” should pay more attention to “pump” than to “because.”',plain:'Self-attention lets each token compute how strongly it should use information from other tokens in the same sequence. The model does not use one fixed connection pattern; the attention pattern changes with the input.',why:'This flexible information routing helps transformers model long-range relationships and context.',technical:'Attention(Q,K,V)=softmax(QKᵀ/√dₖ)V. Queries ask what a token is looking for, keys describe what other tokens offer, and values contain the information to combine.',small:'Each token decides which other tokens matter right now.'},
'embedding':{title:'Embedding',analogy:'Imagine giving every word, machine state, or document a location on a giant map where similar meanings tend to live near each other.',plain:'An embedding is a vector of numbers representing an item in a learned feature space. The individual dimensions usually do not have simple names, but distances and directions can capture useful similarities. Modern NLP, recommendation systems, semantic search, and RAG rely heavily on embeddings.',why:'Embeddings turn complex objects such as text into numbers that models and search systems can compare.',technical:'Embeddings may be learned lookup vectors or generated by neural encoders. Similarity is often measured with cosine similarity or dot product.',small:'A meaningful object turned into a location in number-space.'},
'rag':{title:'RAG — Retrieval-Augmented Generation',analogy:'Instead of asking a technician to answer entirely from memory, first hand them the most relevant pages from the machine manual, then ask the question.',plain:'RAG combines retrieval with generation. Documents are split into chunks, converted into searchable representations, and indexed. When a question arrives, the system retrieves relevant chunks and includes them as context for a language model. The model then answers using that evidence.',why:'RAG is useful when knowledge changes, is private, or is too specific to rely on a model’s training memory. It can also support source citations.',technical:'A typical pipeline is chunking → embeddings → vector/keyword retrieval → optional reranking → prompt construction → LLM generation → grounded evaluation.',small:'Search your documents first, then let the LLM answer with the useful pages beside it.'},
'lora':{title:'LoRA',analogy:'Instead of rebuilding an entire engine to change one behavior, bolt on a small adjustable module while leaving most of the original machine untouched.',plain:'LoRA adapts a pretrained neural network by freezing the original large weight matrices and training small low-rank update matrices. This dramatically reduces the number of trainable parameters and often the memory required for fine-tuning.',why:'It makes useful model adaptation possible on much smaller hardware, including some free-Colab-scale experiments with suitably small models.',technical:'For a frozen weight W, LoRA learns a low-rank update ΔW=BA with rank r much smaller than the original dimensions. At inference the update can be applied alongside or merged into the base weights.',small:'Keep the big model mostly frozen and train a small adapter.'}
};

const aliases={
'features & target':'feature','features':'feature','target':'target','label':'target','labels':'target','gradient':'gradient descent','optimizer':'gradient descent','learning rate':'learning rate','mae':'mae','mse':'mse','r²':'r²','r2':'r²','outlier':'outlier','overfitting':'overfitting','generalization':'overfitting','data leakage':'data leakage','precision':'precision','recall':'recall','confusion matrix':'confusion matrix','random forest':'random forest','knn':'knn','k-nearest neighbors':'knn','svm':'svm','k-means':'k-means','pca':'pca','neuron':'neuron','weights':'weight','weight':'weight','bias':'bias','relu':'relu','backpropagation':'backpropagation','transformer':'transformer','self-attention':'attention','attention':'attention','embedding':'embedding','embeddings':'embedding','rag':'rag','lora':'lora','linear regression':'linear regression'};
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9²-]+/g,' ').replace(/\s+/g,' ').trim()}
function findConcept(text){const n=norm(text);if(E[n])return n;if(aliases[n])return aliases[n];for(const [a,k] of Object.entries(aliases))if(n===norm(a)||n.includes(norm(a)))return k;return null}
function sheet(){let s=document.getElementById('mqExplainerSheet');if(s)return s;s=document.createElement('div');s.id='mqExplainerSheet';s.className='mq-explainer-sheet';s.innerHTML='<div class="mq-explainer-panel"><div class="mq-explainer-head"><div><div class="mq-level-label">MODELQUEST · CONCEPT PORTAL</div><h2 id="mqExpTitle"></h2></div><button class="mq-explainer-close" aria-label="Close">×</button></div><div id="mqExpBody"></div></div>';document.body.appendChild(s);s.addEventListener('click',e=>{if(e.target===s||e.target.closest('.mq-explainer-close'))s.classList.remove('open')});return s}
function openConcept(key){key=findConcept(key)||key;const x=E[key];if(!x)return;const s=sheet();s.querySelector('#mqExpTitle').textContent=x.title;s.querySelector('#mqExpBody').innerHTML=`<div class="mq-depth-tabs"><button class="mq-depth-btn active" data-depth="simple">Understand it</button><button class="mq-depth-btn" data-depth="visual">See the connection</button><button class="mq-depth-btn" data-depth="real">Why it matters</button><button class="mq-depth-btn" data-depth="tech">Go technical</button></div><div class="mq-depth-panel active" data-panel="simple"><div class="mq-explain-analogy"><b>Analogy</b><br>${x.analogy}</div><p>${x.plain}</p><div class="mq-explain-why"><b>In one sentence:</b> ${x.small}</div></div><div class="mq-depth-panel" data-panel="visual"><div class="mq-example-strip"><span>INPUT / PROBLEM</span><strong>${x.small}</strong><b>→ observe the effect</b></div><p>Return to the current lab after reading this and change the related parameter or data point. The purpose of this portal is to give the control a meaning before you touch it—not to make you memorize a definition.</p></div><div class="mq-depth-panel" data-panel="real"><p>${x.why}</p><div class="mq-explain-why"><b>Engineer habit:</b> Ask what changes in the real system if this number, assumption, or metric is wrong.</div></div><div class="mq-depth-panel" data-panel="tech"><p>${x.technical}</p><div class="mq-explain-why">You do not need to memorize this technical layer on the first pass. Come back when the visual behavior already makes sense.</div></div>`;s.querySelectorAll('.mq-depth-btn').forEach(b=>b.onclick=()=>{s.querySelectorAll('.mq-depth-btn').forEach(z=>z.classList.toggle('active',z===b));s.querySelectorAll('.mq-depth-panel').forEach(z=>z.classList.toggle('active',z.dataset.panel===b.dataset.depth))});s.classList.add('open')}
window.MQ_OPEN_EXPLANATION=openConcept;

// Replace short card definitions in the older layer with useful 2–3 sentence explanations.
try{if(typeof cexp==='function'){cexp=(c,p)=>{const k=findConcept(c),x=k&&E[k];return x?`${x.small} ${x.plain}`:`${c} is part of this model because it changes how the system learns, represents data, or judges predictions. Use the lab to change it, watch the consequence, then open the concept portal for the deeper reason.`}}}catch(e){}

// Make the 13 model introductions explain the mechanism, not merely name it.
try{if(typeof MQ_INTRO!=='undefined'){
const richer={
1:'Linear regression is like calibrating a measuring instrument: give it known input/output pairs, then find the straight line that best describes the relationship. In this quest, sensor voltage is the clue and known force is the reference answer. Once the line is learned, a new voltage can be converted into an estimated force.',
2:'Logistic regression does not simply shout YES or NO. It first combines the input clues into a score, bends that score through a sigmoid into a probability-like value, and then uses a threshold to make the final decision. Moving that threshold changes which kinds of mistakes you make.',
3:'KNN works by similarity: a new machine condition asks nearby historical examples to vote. SVM takes a different view and tries to place a boundary with useful breathing room between operating classes. Together they make distance, scaling, and decision boundaries visible.',
4:'A decision tree learns a flowchart from data. At each branch it chooses a question that separates examples into more useful groups, then keeps splitting until it reaches a prediction. Making the tree deeper can discover detail—or memorize noise.',
5:'A Random Forest is a crowd of deliberately different decision trees. Each tree sees a slightly different version of the data and makes its own diagnosis; the forest combines those opinions. Boosting instead builds learners in sequence so later ones concentrate on mistakes left by earlier ones.',
6:'K-Means looks for structure without being told the correct groups. It repeatedly assigns each operating point to the nearest center and moves the centers toward their assigned points. PCA solves a different problem: it finds a simpler view of many measurements while preserving as much variation as possible.',
7:'A neural network is a stack of learnable numerical transformations. Each neuron weights incoming signals, adds a bias, and passes the result through an activation. Training changes thousands of these small knobs so the whole network produces better predictions.',
8:'A model can become excellent at remembering the training set and bad at handling the next production batch. Regularization deliberately limits or disturbs the model during training so it is pushed toward patterns that travel better to unseen data.',
9:'A CNN treats an image as a grid rather than a flat list. Small learned filters slide across the pixels looking for local patterns such as edges, textures, and defect shapes. Deeper layers combine simple patterns into more useful visual features.',
10:'An LSTM processes ordered data while carrying a learned memory forward through time. Gates decide what information to keep, add, or forget. That makes it useful when an earlier vibration or temperature event can affect what happens later.',
11:'A Transformer lets every token look across the sequence and decide which other tokens matter. Attention patterns change with the sentence, so the same word can use different context in different maintenance notes. Stacked attention blocks create the contextual representations used by modern language models.',
12:'LoRA fine-tuning keeps most of a pretrained model frozen and trains only small adapter matrices. That is like modifying a machine with a compact add-on instead of rebuilding every part. The result is far cheaper to adapt and can fit much smaller hardware.',
13:'RAG gives a language model an external memory. It searches manuals, SOPs, and service reports first, selects the most relevant evidence, and puts that evidence beside the question before generation. The difficult engineering work is often retrieval quality—not the final chat box.'};Object.entries(richer).forEach(([i,t])=>{if(MQ_INTRO[i])MQ_INTRO[i].plain=t})}}catch(e){}

// Enrich existing theory portals with analogy-first content while preserving their deeper material.
try{if(typeof MQ_THEORY_TOPICS!=='undefined'){
const map={'how-learning':'gradient descent','metrics':'r²','overfit':'overfitting','leakage':'data leakage','data-basics':'feature','model-structure':'neuron'};for(const [topic,key] of Object.entries(map)){const t=MQ_THEORY_TOPICS[topic],x=E[key];if(t&&x){t.lead=x.small;t.html=`<div class="mq-explain-analogy"><b>Start with an analogy</b><br>${x.analogy}</div><p>${x.plain}</p><div class="mq-explain-why"><b>Why this matters:</b> ${x.why}</div>`+t.html+`<h3>Go technical</h3><p>${x.technical}</p>`}}
if(MQ_THEORY_TOPICS.libraries){MQ_THEORY_TOPICS.libraries.html=`<div class="mq-explain-analogy"><b>Analogy</b><br>Python is the workshop. A library is a toolbox somebody already filled with specialized tools. You still decide what to build; the library saves you from manufacturing every wrench first.</div><p><code>import</code> means “make this toolbox available here.” In <code>import numpy as np</code>, <code>np</code> is just a short nickname. In <code>from sklearn.ensemble import RandomForestClassifier</code>, Python opens scikit-learn, goes to its ensemble section, and brings one specific model tool into your program.</p>`+MQ_THEORY_TOPICS.libraries.html}
}}catch(e){}

function upgradeClickable(root=document){
 const candidates=root.querySelectorAll('.chip,.mq-chip,.concept-link,[data-concept],[data-topic],[data-theory],button');
 candidates.forEach(el=>{if(el.dataset.mqExpBound)return;const key=findConcept(el.dataset.concept||el.dataset.topic||el.textContent);if(!key)return;el.dataset.mqExpBound='1';el.classList.add('mq-detail-trigger');el.addEventListener('dblclick',ev=>{ev.preventDefault();ev.stopPropagation();openConcept(key)});if(el.matches('.chip,.mq-chip')&&!el.closest('button,a')){el.style.cursor='help';el.title='Click for explanation';el.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();openConcept(key)})}})
}
const mo=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1)upgradeClickable(n)});document.addEventListener('DOMContentLoaded',()=>{sheet();upgradeClickable();mo.observe(document.body,{childList:true,subtree:true})});if(document.readyState!=='loading'){sheet();upgradeClickable();mo.observe(document.body,{childList:true,subtree:true})}
})();