/* ModelQuest guided tutorial layer: keeps the original data and utilities, but gives beginners one obvious path. */
const MQ_INTRO={
1:{name:'Linear Regression',plain:'Linear regression learns a straight-line relationship between an input and a number we want to predict. Here the input is practice time and the answer is a score.',input:'Practice hours',output:'Predicted score'},
2:{name:'Logistic Regression',plain:'Logistic regression answers a category question such as yes/no. It first creates a probability-like score, then a threshold turns that score into a decision.',input:'Clues about an example',output:'Probability → class'},
3:{name:'KNN + SVM',plain:'KNN asks which known examples are nearby. SVM tries to draw a useful boundary between groups. Both make the idea of “feature space” visible.',input:'Position in feature space',output:'Class'},
4:{name:'Decision Tree',plain:'A decision tree learns a sequence of questions. Each split sends an example down a branch until it reaches a prediction.',input:'Features',output:'Rule path → prediction'},
5:{name:'Random Forest + Boosting',plain:'Ensembles combine many smaller models. A forest lets many trees vote; boosting builds models in sequence so later models focus on earlier mistakes.',input:'Real tabular data',output:'Stronger combined prediction'},
6:{name:'K-Means + PCA',plain:'This time there are no correct labels. K-Means looks for groups, while PCA gives us a simpler view of data with many dimensions.',input:'Unlabeled examples',output:'Groups + simpler map'},
7:{name:'Neural Network',plain:'A neural network passes numbers through layers of weighted connections. Training changes those weights so predictions become less wrong.',input:'Numbers',output:'Prediction through layers'},
8:{name:'Regularized Neural Network',plain:'A model can memorize training examples instead of learning a useful pattern. Regularization helps it perform better on new data.',input:'Train + validation data',output:'A model that generalizes'},
9:{name:'CNN',plain:'A convolutional neural network looks for small visual patterns such as edges and shapes, then combines them into larger image features.',input:'Image pixels',output:'Image class'},
10:{name:'LSTM',plain:'Sequence models care about order. An LSTM carries useful information forward while deciding what to remember and what to forget.',input:'Ordered values',output:'Next value / sequence prediction'},
11:{name:'Transformer',plain:'Transformers use attention so each token can decide which other tokens matter most. This is the foundation behind modern language models.',input:'Tokens',output:'Context-aware representation'},
12:{name:'LoRA Fine-tuning',plain:'Instead of retraining a huge model, LoRA adds a small trainable adapter while most of the original model stays frozen.',input:'Pretrained model + examples',output:'Adapted model'},
13:{name:'RAG Assistant',plain:'RAG searches your own information first, then gives the useful pieces to a language model. The answer can therefore be grounded in your documents.',input:'Question + documents',output:'Retrieved evidence → answer'}
};

function mqVisual(id){
 const common=`viewBox="0 0 520 300" role="img" aria-label="Visual guide"`;
 if(id===1)return `<svg ${common}><defs><linearGradient id="g1" x1="0" x2="1"><stop stop-color="#49d6c7"/><stop offset="1" stop-color="#9b8cff"/></linearGradient></defs><line x1="54" y1="245" x2="486" y2="245" stroke="#527083"/><line x1="54" y1="245" x2="54" y2="34" stroke="#527083"/><text x="235" y="282" class="mq-axis">practice hours →</text><text x="15" y="28" class="mq-axis">score ↑</text><g fill="#69bfff" opacity=".9"><circle cx="92" cy="214" r="6"/><circle cx="145" cy="191" r="6"/><circle cx="196" cy="171" r="6"/><circle cx="260" cy="132" r="6"/><circle cx="332" cy="103" r="6"/><circle cx="408" cy="62" r="6"/></g><line x1="72" y1="225" x2="455" y2="48" stroke="url(#g1)" stroke-width="5" stroke-linecap="round"/><circle cx="328" cy="105" r="11" fill="#7ee2a8" stroke="#07131d" stroke-width="4"/><text x="342" y="102" fill="#f4fbff" font-size="13">new student</text><text x="342" y="120" fill="#b8c9d6" font-size="12">model reads the line</text></svg>`;
 if(id===2)return `<svg ${common}><text x="35" y="38" class="mq-axis">MODEL SCORE</text><rect x="35" y="70" width="450" height="34" rx="17" fill="#132b3b"/><rect x="35" y="70" width="330" height="34" rx="17" fill="#49d6c7"/><line x1="260" y1="55" x2="260" y2="120" stroke="#ffc96b" stroke-width="4"/><text x="218" y="145" class="mq-axis">threshold</text><text x="35" y="195" fill="#b8c9d6">left of threshold → NO</text><text x="305" y="195" fill="#f4fbff">right of threshold → YES</text><text x="35" y="240" fill="#69bfff">Move the threshold and the decision can change.</text></svg>`;
 if(id===3)return `<svg ${common}><g fill="#69bfff"><circle cx="110" cy="85" r="10"/><circle cx="150" cy="130" r="10"/><circle cx="105" cy="165" r="10"/><circle cx="190" cy="90" r="10"/></g><g fill="#ff8d7a"><circle cx="360" cy="95" r="10"/><circle cx="405" cy="140" r="10"/><circle cx="340" cy="180" r="10"/><circle cx="420" cy="205" r="10"/></g><circle cx="250" cy="135" r="14" fill="#ffc96b"/><circle cx="250" cy="135" r="62" fill="none" stroke="#9b8cff" stroke-width="2" stroke-dasharray="7 6"/><line x1="270" y1="35" x2="270" y2="260" stroke="#49d6c7" stroke-width="4"/><text x="204" y="286" class="mq-axis">neighbors vote • boundary separates</text></svg>`;
 if(id===4)return `<svg ${common}><g fill="#132b3b" stroke="#49d6c7" stroke-width="2"><rect x="190" y="28" width="140" height="44" rx="12"/><rect x="82" y="125" width="140" height="44" rx="12"/><rect x="300" y="125" width="140" height="44" rx="12"/><rect x="55" y="220" width="115" height="42" rx="12"/><rect x="335" y="220" width="115" height="42" rx="12"/></g><g stroke="#527083" stroke-width="3"><line x1="220" y1="72" x2="150" y2="125"/><line x1="300" y1="72" x2="370" y2="125"/><line x1="135" y1="169" x2="112" y2="220"/><line x1="370" y1="169" x2="392" y2="220"/></g><g fill="#f4fbff" font-size="13" text-anchor="middle"><text x="260" y="55">feature &lt; value?</text><text x="152" y="152">another question</text><text x="370" y="152">another question</text><text x="112" y="246">prediction A</text><text x="392" y="246">prediction B</text></g></svg>`;
 if(id===5)return `<svg ${common}><g stroke="#527083" stroke-width="2"><line x1="110" y1="60" x2="260" y2="150"/><line x1="110" y1="150" x2="260" y2="150"/><line x1="110" y1="240" x2="260" y2="150"/><line x1="410" y1="150" x2="300" y2="150"/></g><g fill="#132b3b" stroke="#9b8cff" stroke-width="2"><rect x="45" y="38" width="130" height="44" rx="12"/><rect x="45" y="128" width="130" height="44" rx="12"/><rect x="45" y="218" width="130" height="44" rx="12"/></g><circle cx="280" cy="150" r="42" fill="#49d6c7"/><rect x="365" y="128" width="110" height="44" rx="12" fill="#132b3b" stroke="#7ee2a8" stroke-width="2"/><g fill="#f4fbff" font-size="13" text-anchor="middle"><text x="110" y="65">tree 1</text><text x="110" y="155">tree 2</text><text x="110" y="245">tree 200</text><text x="280" y="155" fill="#05231f" font-weight="800">VOTE</text><text x="420" y="155">prediction</text></g></svg>`;
 if(id===6)return `<svg ${common}><g opacity=".95"><g fill="#69bfff"><circle cx="120" cy="100" r="8"/><circle cx="155" cy="132" r="8"/><circle cx="105" cy="155" r="8"/><circle cx="165" cy="80" r="8"/></g><g fill="#7ee2a8"><circle cx="340" cy="80" r="8"/><circle cx="390" cy="120" r="8"/><circle cx="350" cy="145" r="8"/><circle cx="410" cy="75" r="8"/></g><g fill="#ff8d7a"><circle cx="240" cy="215" r="8"/><circle cx="285" cy="230" r="8"/><circle cx="220" cy="250" r="8"/><circle cx="300" cy="195" r="8"/></g></g><g fill="#ffc96b" stroke="#07131d" stroke-width="3"><path d="M135 110 l10 20 h-20z"/><path d="M370 105 l10 20 h-20z"/><path d="M260 225 l10 20 h-20z"/></g><text x="160" y="290" class="mq-axis">K-Means moves centers toward groups</text></svg>`;
 if(id===7)return `<svg ${common}><g stroke="#527083" stroke-width="2">${[[90,75],[90,150],[90,225]].flatMap(a=>[[255,60],[255,120],[255,180],[255,240]].map(b=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`)).join('')}${[[255,60],[255,120],[255,180],[255,240]].map(a=>`<line x1="${a[0]}" y1="${a[1]}" x2="430" y2="150"/>`).join('')}</g><g fill="#69bfff"><circle cx="90" cy="75" r="16"/><circle cx="90" cy="150" r="16"/><circle cx="90" cy="225" r="16"/></g><g fill="#9b8cff"><circle cx="255" cy="60" r="16"/><circle cx="255" cy="120" r="16"/><circle cx="255" cy="180" r="16"/><circle cx="255" cy="240" r="16"/></g><circle cx="430" cy="150" r="19" fill="#7ee2a8"/><g class="mq-axis"><text x="53" y="285">inputs</text><text x="226" y="285">hidden layer</text><text x="405" y="285">output</text></g></svg>`;
 if(id===8)return `<svg ${common}><polyline points="55,215 110,170 165,132 220,102 275,82 330,68 385,58 455,50" fill="none" stroke="#49d6c7" stroke-width="5"/><polyline points="55,225 110,185 165,150 220,122 275,110 330,118 385,145 455,190" fill="none" stroke="#ff8d7a" stroke-width="5"/><text x="360" y="42" fill="#49d6c7">training</text><text x="385" y="215" fill="#ff8d7a">validation</text><text x="195" y="275" class="mq-axis">training time →</text></svg>`;
 if(id===9)return `<svg ${common}><g transform="translate(55,50)">${Array.from({length:8},(_,r)=>Array.from({length:8},(_,c)=>`<rect x="${c*22}" y="${r*22}" width="20" height="20" fill="${(r>1&&r<6&&c>2&&c<5)?'#69bfff':'#132b3b'}" stroke="#284459"/>`).join('')).join('')}</g><rect x="99" y="94" width="66" height="66" fill="none" stroke="#ffc96b" stroke-width="4"/><path d="M245 135 h70" stroke="#527083" stroke-width="3" marker-end="url(#none)"/><g transform="translate(340,85)">${Array.from({length:3},(_,r)=>Array.from({length:3},(_,c)=>`<rect x="${c*42}" y="${r*42}" width="38" height="38" rx="5" fill="${c===1?'#49d6c7':'#132b3b'}" stroke="#284459"/>`).join('')).join('')}</g><text x="55" y="260" class="mq-axis">small filter slides across image</text></svg>`;
 if(id===10)return `<svg ${common}><g stroke="#527083" stroke-width="3">${[85,190,295].map(x=>`<line x1="${x+65}" y1="145" x2="${x+105}" y2="145"/>`).join('')}</g><g fill="#132b3b" stroke="#9b8cff" stroke-width="3"><rect x="40" y="105" width="110" height="80" rx="18"/><rect x="190" y="105" width="110" height="80" rx="18"/><rect x="340" y="105" width="110" height="80" rx="18"/></g><g fill="#f4fbff" text-anchor="middle"><text x="95" y="150">step 1</text><text x="245" y="150">step 2</text><text x="395" y="150">step 3</text></g><text x="140" y="230" class="mq-axis">hidden memory travels forward →</text></svg>`;
 if(id===11)return `<svg ${common}><g fill="#132b3b" stroke="#284459"><rect x="45" y="125" width="85" height="46" rx="12"/><rect x="165" y="125" width="85" height="46" rx="12"/><rect x="285" y="125" width="85" height="46" rx="12"/><rect x="405" y="125" width="70" height="46" rx="12"/></g><g stroke-width="4" fill="none"><path d="M87 125 Q220 30 440 125" stroke="#9b8cff"/><path d="M207 125 Q310 65 440 125" stroke="#49d6c7"/><path d="M327 125 Q390 90 440 125" stroke="#ffc96b"/></g><g fill="#f4fbff" text-anchor="middle"><text x="87" y="154">The</text><text x="207" y="154">dog</text><text x="327" y="154">ran</text><text x="440" y="154">fast</text></g><text x="125" y="240" class="mq-axis">attention connects tokens that matter</text></svg>`;
 if(id===12)return `<svg ${common}><rect x="55" y="78" width="260" height="140" rx="24" fill="#132b3b" stroke="#69bfff" stroke-width="3"/><text x="185" y="135" fill="#f4fbff" text-anchor="middle" font-size="18">PRETRAINED MODEL</text><text x="185" y="165" fill="#b8c9d6" text-anchor="middle">mostly frozen</text><rect x="335" y="105" width="130" height="86" rx="18" fill="#2b2445" stroke="#9b8cff" stroke-width="3"/><text x="400" y="140" fill="#f4fbff" text-anchor="middle" font-size="17">LoRA</text><text x="400" y="164" fill="#b8c9d6" text-anchor="middle">small adapter</text><path d="M315 148 h20" stroke="#7ee2a8" stroke-width="5"/><text x="98" y="260" class="mq-axis">train a small part instead of everything</text></svg>`;
 return `<svg ${common}><g fill="#132b3b" stroke="#284459" stroke-width="2"><rect x="25" y="115" width="90" height="55" rx="13"/><rect x="150" y="115" width="100" height="55" rx="13"/><rect x="285" y="115" width="95" height="55" rx="13"/><rect x="415" y="115" width="80" height="55" rx="13"/></g><g stroke="#49d6c7" stroke-width="4"><line x1="115" y1="142" x2="150" y2="142"/><line x1="250" y1="142" x2="285" y2="142"/><line x1="380" y1="142" x2="415" y2="142"/></g><g fill="#f4fbff" text-anchor="middle"><text x="70" y="147">question</text><text x="200" y="147">retrieve</text><text x="332" y="147">evidence</text><text x="455" y="147">answer</text></g><text x="83" y="235" class="mq-axis">RAG = search first, answer second</text></svg>`;
}

function mqAnnotatedCode(id,code){
 const lines=code.split('\n'); const out=[]; let imports=false,split=false,model=false,train=false,predict=false,measure=false;
 out.push(`# MODEL ${id} — READ THIS TOP TO BOTTOM`);
 out.push(`# The comments explain WHY each block exists. You do not need to memorize the syntax.`);
 for(const line of lines){
  const t=line.trim();
  if(t.startsWith('# MODEL')) continue;
  if(!imports&&(t.startsWith('import ')||t.startsWith('from '))){out.push('', '# 1) LOAD TOOLS — these libraries give us ready-made math, data and ML functions.');imports=true}
  if(!split&&t.includes('train_test_split(')){out.push('', '# 3) SPLIT THE DATA — training data is for learning; test data is the unseen exam.');split=true}
  if(!model&&(/model\s*=|models\s*=|Sequential\(|KMeans\(|pipeline\(/.test(t))){out.push('', '# 4) BUILD / CHOOSE THE MODEL — this decides what kind of pattern can be learned.');model=true}
  if(!train&&(t.includes('.fit(')||t.includes('model.train(')||t.includes('trainer.train('))){out.push('', '# 5) TRAIN — the model looks at examples and adjusts itself to reduce mistakes.');train=true}
  if(!predict&&(t.includes('.predict(')||t.includes('predict_proba')||t.includes('generate('))){out.push('', '# 6) PREDICT — now ask the trained model to answer using data it did not learn from.');predict=true}
  if(!measure&&(t.includes('mean_absolute_error')||t.includes('classification_report')||t.includes('score(')||t.includes('accuracy')||t.includes('silhouette_score'))){out.push('', '# 7) MEASURE — never trust “it looks good”; use a metric and inspect mistakes.');measure=true}
  if(/^X\s*=/.test(t)) out.push('# X = FEATURES: the clues we give the model.');
  if(/^y\s*=/.test(t)) out.push('# y = TARGET/LABEL: the answer we want it to learn.');
  out.push(line);
 }
 return out.join('\n');
}

function mqNext(n,label){return `<div class="mq-nextstep"><a class="btn primary" href="#mq-step-${n}">Next: ${label} ↓</a></div>`}
function mqStepHead(n,title,sub){return `<div class="mq-stephead"><div class="mq-stepnum">${n}</div><div><h2>${title}</h2><p>${sub}</p></div></div>`}

showHome=function(){
 cur=st.current||1; $('#homeHero').style.display='block';
 $('#view').innerHTML=`<section class="section"><div class="mq-home-start"><h2>Not sure where to go? Start here.</h2><p>ModelQuest is meant to be followed in order the first time. You never need to choose the next page: open Model 1 and use the big <b>Next</b> button at the bottom of each section.</p><div class="actions"><button class="btn primary" data-go="${st.current||1}">▶ ${st.current>1?'Continue Model '+st.current:'Start Model 1'}</button></div><div class="mq-home-stages"><div><b>1 · Foundations</b><span>Predictions, classes, neighbors, trees</span></div><div><b>2 · Real ML</b><span>Messy data, ensembles, clusters</span></div><div><b>3 · Neural Networks</b><span>Layers, generalization, images, sequences</span></div><div><b>4 · Modern AI</b><span>Transformers, LoRA, RAG</span></div></div></div><div class="stitle"><div><h2>The full 13-model path</h2><p>Recommended order is left to right. Peeking ahead is allowed.</p></div></div><div class="grid two homecards">${PROJECTS.map(nav).join('')}</div></section>`;
 $$('[data-go]').forEach(b=>b.onclick=()=>go(+b.dataset.go)); renderNav(); progress(); scrollTo({top:0,behavior:'smooth'});
};

renderProject=function(p){
 const intro=MQ_INTRO[p.id],ms=st.missions[p.id]||{},done=Object.values(ms).filter(Boolean).length,code=mqAnnotatedCode(p.id,p.code);
 $('#view').innerHTML=`
 <section class="hero"><div class="mq-breadcrumb">Course path › ${stageOf(p.id)} › Model ${p.id} of 13</div><span class="mq-kicker">YOU ARE HERE · MODEL ${p.id}</span><h1>${esc(p.title)}</h1><p class="mq-hero-note"><b>${esc(p.subtitle)}</b> — ${esc(p.goal)}</p><div class="mq-hero-tip"><b>New here?</b> Do not jump around. Press <b>Start this lesson</b>, then use the green Next button after every section.</div><div class="actions"><a class="btn primary" href="#mq-step-1">▶ Start this lesson</a><button class="btn" id="stuck">I’m stuck</button><button class="btn" id="path">Course map</button></div><div class="progress"><div class="bar"><i style="width:${Math.round(done/p.missions.length*100)}%"></i></div><b>${done}/${p.missions.length} mission checks</b></div></section>
 <section class="mq-guide"><div class="mq-guide-top"><div><h2>Follow this route — 6 steps</h2><p>There is one intended flow. Each step prepares you for the next.</p></div><span class="tag">ABOUT ${esc(p.time)}</span></div><div class="mq-route"><a href="#mq-step-1"><b>1</b><span>The problem</span></a><a href="#mq-step-2"><b>2</b><span>Picture it</span></a><a href="#mq-step-3"><b>3</b><span>Play with it</span></a><a href="#mq-step-4"><b>4</b><span>How it works</span></a><a href="#mq-step-5"><b>5</b><span>Build in Colab</span></a><a href="#mq-step-6"><b>6</b><span>Challenge + finish</span></a></div></section>

 <section class="mq-step" id="mq-step-1">${mqStepHead(1,'What problem are we solving?','Understand the goal before touching code.')}<div class="mq-explain"><div class="mq-story"><div class="eyebrow">THE QUESTION</div><h3>${esc(p.hook)}</h3><p>${esc(intro.plain)}</p><div class="mq-simple"><b>Input</b><p>${esc(intro.input)} — information the model is allowed to see.</p></div><div class="mq-simple"><b>Output</b><p>${esc(intro.output)} — the answer we want from the model.</p></div><div class="mq-simple warn"><b>Important</b><p>The computer is not “thinking” like a person. It is finding a numerical pattern in examples.</p></div></div><div class="mq-picture">${mqVisual(p.id)}<div class="mq-legend"><span class="mq-dot"><i style="background:var(--sky)"></i>examples/data</span><span class="mq-dot"><i style="background:var(--green)"></i>new prediction</span><span class="mq-dot"><i style="background:var(--violet)"></i>learned pattern</span></div></div></div>${mqNext(2,'see the picture')}</section>

 <section class="mq-step" id="mq-step-2">${mqStepHead(2,'Picture the model','A visual mental model comes before formulas.')}<div class="card"><div class="mq-why-grid"><div class="mq-why"><b>What goes in?</b><p>${esc(intro.input)}. In ML these inputs are usually called <b>features</b>.</p></div><div class="mq-why"><b>What is learned?</b><p>The model adjusts its internal parameters using training examples. The exact parameters depend on the model family.</p></div><div class="mq-why"><b>What comes out?</b><p>${esc(intro.output)}. We compare it with reality to see how wrong the model is.</p></div></div><div class="mq-check"><div><b>Training</b><br>The model is allowed to learn from these examples.</div><div><b>Testing</b><br>These are kept unseen until we check whether learning actually worked.</div></div></div>${mqNext(3,'try the interactive lab')}</section>

 <section class="mq-step" id="mq-step-3">${mqStepHead(3,'Play with the idea','Change one thing, predict first, then observe.')}<div class="lab"><div class="labhead"><b>${esc(p.subtitle)} Interactive Lab</b><small>No Python needed</small></div><div class="labbody"><div class="mq-labguide"><div><b>1 · PREDICT</b><span>Before moving a control, guess what will happen.</span></div><div><b>2 · CHANGE</b><span>Move only one control so you know what caused the change.</span></div><div><b>3 · EXPLAIN</b><span>Say why the output changed in your own words.</span></div></div><div id="lab"></div></div></div>${mqNext(4,'understand how it works')}</section>

 <section class="mq-step" id="mq-step-4">${mqStepHead(4,'How does the model work?','Learn only the pieces you just saw in action.')}<div class="mq-explain"><div class="mq-story"><h3>${esc(intro.name)} in plain English</h3><p>${esc(intro.plain)}</p><div class="mq-simple"><b>Do not memorize definitions.</b><p>Ask: what information goes in, what pattern can this model represent, how does it learn, and how do I know if its answer is useful?</p></div></div><div class="grid two">${p.concepts.slice(0,8).map(c=>`<div class="card"><h3>${esc(c)}</h3><p>${esc(cexp(c,p))}</p></div>`).join('')}</div></div>${mqNext(5,'build the real model')}</section>

 <section class="mq-step" id="mq-step-5">${mqStepHead(5,'Build the real model in Colab','The code is commented and meant to be read top to bottom.')}<div class="mq-code-map"><div><b>1 · TOOLS</b><span>Import libraries</span></div><div><b>2 · DATA</b><span>Load/create examples</span></div><div><b>3 · SPLIT</b><span>Train vs test</span></div><div><b>4 · MODEL</b><span>Choose structure</span></div><div><b>5 · TRAIN</b><span>Learn pattern</span></div><div><b>6 · CHECK</b><span>Predict + measure</span></div></div><div class="mq-code-note"><strong>How to use this:</strong> first read the comments, then press Copy code. Paste it into one fresh Colab cell and run it. After it works, change only the value suggested in the challenge.</div><div class="code"><div class="codetop"><span>Python · fully commented starter · Model ${p.id}</span><div><button class="copy" id="copy">Copy code</button> <button class="copy" id="colab">Copy + open Colab ↗</button></div></div><div class="scroll"><pre>${esc(code)}</pre></div></div><div class="card" style="margin-top:10px"><h3>If it does not work</h3><p>Do not randomly change code. Read the last error line → check variable names → print shapes/types → check the exact line that failed → search the official docs for that function. Use <b>I’m stuck</b> if you need the checklist.</p></div>${mqNext(6,'test yourself and finish')}</section>

 <section class="mq-step" id="mq-step-6">${mqStepHead(6,'Use it like a real ML builder','A tutorial is finished only when you can explain what happened.')}<div class="grid two"><div class="card challenge"><span class="tag">BOSS CHALLENGE</span><h3 style="margin-top:10px">${esc(p.challenge)}</h3><p>Before changing the code, write one prediction: “I think ___ will happen because ___.” Then test it.</p></div><div class="card"><h3>Mission checklist</h3><p class="mq-missions-note">Mark these only when you can explain them without copying the wording.</p><div class="missions">${p.missions.map((m,i)=>`<div class="mission"><span class="num">${i+1}</span><b>${esc(m)}</b><button data-mission="${i}">${ms[i]?'✓ Done':'Mark done'}</button></div>`).join('')}</div></div></div><div class="stitle" style="margin-top:16px"><div><h2>Real-world traps</h2><p>These are the mistakes that clean textbook examples often hide.</p></div></div><div class="grid three">${p.real.map((r,i)=>`<div class="card trap ${i===0?'bad':''}"><h3>${i===0?'⚠ Watch this':'Smart habit'}</h3><p>${esc(r)}</p></div>`).join('')}</div><div class="stitle" style="margin-top:16px"><div><h2>Where to verify and learn more</h2><p>Official documentation first; papers for the original idea; community sources for messy practical cases.</p></div></div><div class="links">${p.sources.map(([t,n,u])=>`<a class="link" href="${u}" target="_blank" rel="noopener"><span class="tag">${esc(t)}</span><span><b style="color:var(--text)">${esc(n)}</b><br>${esc(new URL(u).hostname)}</span></a>`).join('')}</div><div class="actions" style="margin-top:16px"><button class="btn primary" id="complete">${st.completed[p.id]?'✓ Project completed':'✓ I finished this model'}</button><button class="btn" id="next">Next model →</button><button class="btn" id="path2">Course map</button></div></section>`;
 $('#stuck').onclick=openStuck; $('#path').onclick=$('#path2').onclick=showHome; $('#copy').onclick=()=>copy(code); $('#colab').onclick=async()=>{await copy(code);window.open('https://colab.research.google.com/#create=true','_blank','noopener')}; $('#complete').onclick=()=>{st.completed[p.id]=!st.completed[p.id];save();renderProject(p);toast(st.completed[p.id]?'Project complete':'Marked incomplete')}; $('#next').onclick=()=>go(p.id+1); $$('[data-mission]').forEach(b=>b.onclick=()=>{st.missions[p.id]=st.missions[p.id]||{};st.missions[p.id][b.dataset.mission]=!st.missions[p.id][b.dataset.mission];save();renderProject(p)}); renderLab(p.id);
};

const mqLegacyRenderLab=renderLab;
renderLab=function(id){
 if(id!==1){mqLegacyRenderLab(id);const box=$('#lab');if(box)box.insertAdjacentHTML('beforeend',`<div class="mq-observe" style="margin-top:12px"><strong>What to notice:</strong> Do not chase a “good” number yet. Move one control and explain which output changed and why.</div>`);return}
 const e=$('#lab');
 e.innerHTML=`<div class="mq-linear-wrap"><div class="mq-chart"><svg id="linChart" viewBox="0 0 620 360" role="img" aria-label="Practice hours and score scatter plot with regression line"><line x1="55" y1="305" x2="590" y2="305" stroke="#527083"/><line x1="55" y1="305" x2="55" y2="30" stroke="#527083"/><text x="250" y="345" class="mq-axis">practice hours →</text><text x="12" y="25" class="mq-axis">score ↑</text><g id="trainPts" fill="#69bfff" opacity=".8">${[[1,2],[2,-1],[3,1],[4,-2],[5,2],[6,-1],[7,1],[8,-2],[9,2],[10,-1],[11,1]].map(([x,d])=>`<circle data-x="${x}" data-base="${d}" cx="${55+x*44}" cy="150" r="6"/>`).join('')}</g><line x1="77" y1="270" x2="583" y2="52" stroke="#9b8cff" stroke-width="5" stroke-linecap="round"/><circle id="predPoint" cx="275" cy="180" r="11" fill="#7ee2a8" stroke="#07131d" stroke-width="4"/><line id="predGuide" x1="275" x2="275" y1="305" y2="180" stroke="#7ee2a8" stroke-dasharray="5 5"/><text id="predLabel" x="290" y="170" fill="#f4fbff" font-size="13">prediction</text></svg></div><div class="mq-controls-panel"><div class="control"><label><span>Practice hours</span><b id="aVal">5</b></label><input id="a2" type="range" min="0.5" max="12" value="5" step="0.5"></div><div class="control"><label><span>Data messiness (noise)</span><b id="bVal">6</b></label><input id="b2" type="range" min="0" max="18" value="6" step="1"></div><div class="mq-readout"><small>MODEL PREDICTION</small><b id="scoreOut">61</b><small>predicted score out of 100</small></div><div class="mq-readout"><small>ROUGH UNCERTAINTY FROM NOISE</small><b id="rangeOut">55–67</b><small>not a formal confidence interval—just a visual reminder that data is messy</small></div><div class="mq-observe" id="obs"><strong>Try this:</strong> move practice hours first. The green point should slide along the learned line.</div></div></div>`;
 const a=$('#a2'),b=$('#b2'),pts=$$('#trainPts circle');
 const update=()=>{const h=+a.value,n=+b.value,p=Math.max(0,Math.min(100,35+5.2*h));$('#aVal').textContent=h;$('#bVal').textContent=n;$('#scoreOut').textContent=Math.round(p);$('#rangeOut').textContent=`${Math.max(0,Math.round(p-n))}–${Math.min(100,Math.round(p+n))}`;const x=55+h*44,y=305-(p/100)*250;$('#predPoint').setAttribute('cx',x);$('#predPoint').setAttribute('cy',y);$('#predGuide').setAttribute('x1',x);$('#predGuide').setAttribute('x2',x);$('#predGuide').setAttribute('y2',y);$('#predLabel').setAttribute('x',Math.min(515,x+14));$('#predLabel').setAttribute('y',Math.max(35,y-12));pts.forEach(pt=>{const hx=+pt.dataset.x,dev=+pt.dataset.base;const sy=Math.max(0,Math.min(100,35+5.2*hx+dev*n));pt.setAttribute('cy',305-(sy/100)*250)});$('#obs').innerHTML=n>12?'<strong>Notice:</strong> the blue examples are scattered far from the line. The same practice time can now have very different scores, so predictions are less reliable.':'<strong>Notice:</strong> more practice moves the prediction upward because the training examples contain an upward pattern. Noise changes how trustworthy that pattern feels.'};
 a.oninput=b.oninput=update;update();
};

// Re-render the current screen with the new guided layout as soon as this file loads.
if($('#homeHero')&&$('#homeHero').style.display==='none') go(cur); else showHome();
