/* ModelQuest labs — direct-manipulation visuals for Models 2–13. */
(()=>{
  const CFG={
    2:{title:'Quality Gate · Threshold Lab',a:['Decision threshold',0.05,0.95,0.50,0.05],b:['Cost of missing a defect',1,10,6,1],mission:'Move the threshold. Watch the same fixed scores create different shop-floor decisions, then connect those decisions to the confusion matrix.'},
    3:{title:'Machine State · Distance Lab',a:['Neighbors (K)',1,9,3,2],b:['Temperature scale',1,20,1,1],mission:'Break distance by changing only a unit scale. Compare the distorted geometry with the repaired, scaled geometry side by side.'},
    4:{title:'Late Shipment · Tree Depth Lab',a:['Maximum depth',1,10,3,1],b:['Minimum samples per leaf',1,20,5,1],mission:'Grow the tree. Training fit keeps improving; unseen performance eventually stops improving. See both the tree and the score curves.'},
    5:{title:'Predictive Maintenance · Forest + Leakage Lab',a:['Number of trees',5,200,50,5],b:['Failure importance',1,10,5,1],mission:'Compare a majority baseline, an honest forest, and a leaked forest. A suspiciously perfect score is a warning, not a victory.',demo:'Inject future_repair_flag'},
    6:{title:'Hidden Modes · K-Means + PCA Lab',a:['Clusters (K)',2,8,3,1],b:['PCA view angle',0,90,25,5],mission:'Force K from 2 to 8. Watch the clusters and a silhouette-style quality curve together. The algorithm always gives K groups; reality may not.'},
    7:{title:'Sensor Fusion · Neural Network Lab',a:['Hidden neurons',1,10,4,1],b:['Learning rate',0.01,0.50,0.12,0.01],mission:'Change capacity and update size. Take training steps and watch structure and loss together; a step that is too large can increase loss.',action:'Train one step'},
    8:{title:'New-Batch Test · Generalization Lab',a:['Model complexity',1,10,5,1],b:['Regularization strength',0,10,3,1],mission:'Compare old-batch fit with new-batch performance. Then shift the supplier batch and see why world-change is not the same as overfitting.',demo:'Shift supplier batch'},
    9:{title:'Surface Defect Vision · CNN Filter Lab',a:['Edge filter strength',-2,2,1,1],b:['Pooling size',1,4,2,1],mission:'See a local image patch, the filter response, and what pooling keeps. Then add a lighting shift without changing the defect.',demo:'Add lighting shift'},
    10:{title:'Energy Forecast · Memory Lab',a:['History length',1,12,5,1],b:['Signal noise',0,10,2,1],mission:'Two sequences can end at the same current reading but imply different futures. Change how much history the model is allowed to see.'},
    11:{title:'Maintenance Notes · Attention Lab',a:['Attention sharpness',1,10,5,1],b:['Focus token',0,7,4,1],mission:'Choose a token and watch contextual links change. Attention is a weighted information flow, not a magic explanation of human reasoning.'},
    12:{title:'Technician Report Adapter · LoRA Lab',a:['LoRA rank',1,32,8,1],b:['Quantization bits',4,16,8,4],mission:'Change adapter rank and storage precision. See what stays frozen, what trains, and how capacity and memory move.'},
    13:{title:'Engineering Copilot · RAG Lab',a:['Top-K chunks',1,6,3,1],b:['Chunk size',100,800,350,50],mission:'Inspect retrieved evidence before generation. Increase Top-K until irrelevant chunks enter and see retrieval quality fall.',demo:'Inject irrelevant chunk'}
  };

  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>c==='&'?'&amp;':c==='<'?'&lt;':c==='>'?'&gt;':c==='"'?'&quot;':'&#39;');
  const fmt=v=>Number.isInteger(v)?String(v):Number(v).toFixed(2);
  const line=(x1,y1,x2,y2,extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" ${extra}/>`;
  const text=(x,y,t,extra='')=>`<text x="${x}" y="${y}" ${extra}>${esc(t)}</text>`;
  const rect=(x,y,w,h,extra='')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" ${extra}/>`;
  const card=(k,v)=>`<div><small>${esc(k)}</small><b>${esc(v)}</b></div>`;

  function shell(id){
    const c=CFG[id];
    if(!c)return '<div class="mq10-error">No interactive lab is defined for this model yet.</div>';
    const range=(key,x)=>`<label class="mq10-control"><span>${esc(x[0])} <b data-out="${key}">${x[3]}</b></span><input data-control="${key}" type="range" min="${x[1]}" max="${x[2]}" value="${x[3]}" step="${x[4]}"></label>`;
    return `<div class="mq10-lab" id="mq10Lab" data-model="${id}">
      <div class="mq10-head"><div><small>LIVE TRY IT LAB</small><h2>${esc(c.title)}</h2><p>${esc(c.mission)}</p></div><div class="mq10-rule">Predict → change one thing → observe → explain why</div></div>
      <div class="mq10-grid"><div class="mq10-stage"><svg data-viz viewBox="0 0 700 430" role="img" aria-label="Interactive model visualization"></svg><div class="mq10-caption" data-caption></div></div>
      <aside class="mq10-controls">${range('a',c.a)}${range('b',c.b)}${c.action?`<button type="button" class="mq10-action" data-action>${esc(c.action)}</button>`:''}${c.demo?`<button type="button" class="mq10-action" data-demo>${esc(c.demo)}</button>`:''}<button type="button" class="mq10-reset" data-reset>Reset lab</button><div class="mq10-metrics" data-metrics></div><div class="mq10-explain" data-explain></div></aside></div>
    </div>`;
  }

  window.mqLabFor=id=>shell(Number(id));
  window.mqInitLab=id=>init(Number(id));

  function init(id){
    const root=document.querySelector('#mq10Lab');
    if(!root||Number(root.dataset.model)!==id)return;
    const c=CFG[id], q=s=>root.querySelector(s), a=q('[data-control="a"]'), b=q('[data-control="b"]');
    const state={steps:0,loss:1,demo:false};
    const val=el=>Number(el.value);
    function set(svg,metrics,explain,caption){q('[data-viz]').innerHTML=svg;q('[data-metrics]').innerHTML=metrics;q('[data-explain]').innerHTML=explain;q('[data-caption]').innerHTML=caption||'';q('[data-out="a"]').textContent=fmt(val(a));q('[data-out="b"]').textContent=fmt(val(b));}

    function draw2(){
      const t=val(a),cost=val(b),rows=[['PASS',.12],['PASS',.24],['FAIL',.31],['PASS',.41],['FAIL',.48],['PASS',.54],['FAIL',.58],['PASS',.63],['FAIL',.72],['FAIL',.82],['FAIL',.91]];
      let tp=0,tn=0,fp=0,fn=0,dots='',x=s=>45+s*380;
      rows.forEach(([actual,s],i)=>{const pred=s>=t,real=actual==='FAIL';if(pred&&real)tp++;else if(pred&&!real)fp++;else if(!pred&&real)fn++;else tn++;dots+=`<circle cx="${x(s)}" cy="${90+(i%4)*48}" r="10" fill="${real?'#fff':'#555'}" stroke="${pred?'#fff':'#222'}" stroke-width="4"><title>${actual} · fail score ${s}</title></circle>`});
      const recall=tp/(tp+fn||1),precision=tp/(tp+fp||1),weighted=fn*cost+fp;
      const cmx=475,cmy=95,cw=82,ch=72;
      let cm=text(cmx,cmy-28,'CONFUSION MATRIX','fill="#999" font-size="13"')+text(cmx-25,cmy-8,'pred PASS','fill="#777" font-size="11"')+text(cmx+75,cmy-8,'pred FAIL','fill="#777" font-size="11"');
      [[tn,'good kept'],[fp,'false reject'],[fn,'missed defect'],[tp,'defect caught']].forEach((z,i)=>{const xx=cmx+(i%2)*cw,yy=cmy+Math.floor(i/2)*ch;cm+=rect(xx,yy,cw-6,ch-6,`rx="9" fill="${i===2?'#161616':'#333'}" stroke="${i===2?'#fff':'#555'}"`)+text(xx+8,yy+27,String(z[0]),'fill="#fff" font-size="22"')+text(xx+8,yy+48,z[1],'fill="#aaa" font-size="10"')});
      set(line(45,305,425,305,'stroke="#555"')+line(x(t),45,x(t),315,'stroke="#fff" stroke-width="3" stroke-dasharray="7 7"')+dots+text(45,350,'low FAIL score','fill="#777"')+text(335,350,'high FAIL score','fill="#777"')+text(Math.min(365,x(t)+8),64,'threshold '+t.toFixed(2),'fill="#fff"')+cm,
        card('defects caught',(recall*100).toFixed(0)+'%')+card('precision',(precision*100).toFixed(0)+'%')+card('mistake cost',String(weighted)),
        '<b>Why:</b> the model scores do not move. Only the cutoff moves. Lowering it catches more defects, but can reject more good parts. The confusion matrix shows exactly which kind of mistake changed.',
        'Filled white dots are real defects. A white outline means the current threshold predicts FAIL.');
    }

    function draw3(){
      const k=Math.round(val(a)),scale=val(b),pts=[[-1.8,-.8,'NORMAL'],[-1.2,.1,'NORMAL'],[-.7,-.5,'NORMAL'],[.8,.7,'UNBALANCED'],[1.2,.2,'UNBALANCED'],[1.7,.9,'UNBALANCED'],[-.2,1.7,'OVERLOAD'],[.3,1.4,'OVERLOAD'],[-.5,1.1,'OVERLOAD']],query=[.1,.45];
      function pane(cx,repair){const sx=x=>cx+x*82,sy=y=>210-y*58,sc=repair?1:scale,dist=pts.map((p,i)=>({i,d:Math.hypot(p[0]-query[0],(p[1]-query[1])*sc),p})).sort((u,v)=>u.d-v.d),near=dist.slice(0,k),votes={};near.forEach(n=>votes[n.p[2]]=(votes[n.p[2]]||0)+1);const winner=Object.entries(votes).sort((u,v)=>v[1]-u[1])[0]?.[0]||'?';let h=line(cx-145,210,cx+145,210,'stroke="#333"')+line(cx,55,cx,365,'stroke="#333"');pts.forEach((p,i)=>{const chosen=near.some(n=>n.i===i);if(chosen)h+=line(sx(query[0]),sy(query[1]),sx(p[0]),sy(p[1]),'stroke="#777" stroke-dasharray="4 5"');h+=`<circle cx="${sx(p[0])}" cy="${sy(p[1])}" r="8" fill="${p[2]==='NORMAL'?'#ddd':p[2]==='UNBALANCED'?'#888':'#444'}" stroke="${chosen?'#fff':'#222'}" stroke-width="3"/>`});h+=`<circle cx="${sx(query[0])}" cy="${sy(query[1])}" r="11" fill="#fff" stroke="#000" stroke-width="3"/>`+text(cx-135,40,repair?'SCALED / REPAIRED':'RAW / DISTORTED',`fill="${repair?'#fff':'#888'}" font-size="13"`)+text(cx-135,395,'prediction: '+winner,'fill="#bbb" font-size="13"');return {h,winner}}
      const L=pane(185,false),R=pane(525,true);
      set(L.h+R.h+line(350,30,350,405,'stroke="#333" stroke-dasharray="5 8"'),card('raw prediction',L.winner)+card('scaled prediction',R.winner)+card('temperature scale',scale+'×'),'<b>Why:</b> multiplying a feature by a large number changes distance even though the machine did not physically change. Scaling repairs the numerical geometry so units do not dominate similarity.','The same unknown reading appears in both panes. Only the distance geometry is different.');
    }

    function draw4(){
      const depth=val(a),leaf=val(b),train=Math.min(99,58+depth*5.2),test=Math.max(52,58+depth*7-Math.max(0,depth-5)**2*2.2-leaf*.35);
      let h=text(35,35,'TREE','fill="#999" font-size="12"');const levels=Math.min(4,depth);for(let d=0;d<levels;d++){const n=2**d;for(let i=0;i<n;i++){const x=170+(i+.5)*290/n-145,y=80+d*72;h+=rect(x-34,y-16,68,32,'rx="8" fill="#171717" stroke="#777"')+text(x,y+4,d===0?'queue?':d===1?'distance?':'condition?','fill="#ccc" text-anchor="middle" font-size="10"');if(d<levels-1){h+=line(x,y+16,170+(i*2+.5)*290/(n*2)-145,y+55,'stroke="#444"')+line(x,y+16,170+(i*2+1.5)*290/(n*2)-145,y+55,'stroke="#444"')}}}
      const x0=390,y0=340;h+=text(390,35,'FIT VS DEPTH','fill="#999" font-size="12"')+line(390,340,655,340,'stroke="#555"')+line(390,65,390,340,'stroke="#555"');let p1='',p2='';for(let d=1;d<=10;d++){const tr=Math.min(99,58+d*5.2),te=Math.max(52,58+d*7-Math.max(0,d-5)**2*2.2-leaf*.35),xx=390+(d-1)*29,yt=340-(tr-45)*4.4,ye=340-(te-45)*4.4;p1+=(d===1?'M':'L')+xx+' '+yt+' ';p2+=(d===1?'M':'L')+xx+' '+ye+' ';if(d===depth)h+=line(xx,65,xx,340,'stroke="#777" stroke-dasharray="4 5"')}
      h+=`<path d="${p1}" fill="none" stroke="#fff" stroke-width="3"/><path d="${p2}" fill="none" stroke="#777" stroke-width="3"/>`+text(400,370,'white = train · gray = unseen','fill="#888" font-size="11"');
      set(h,card('training fit',train.toFixed(0)+'%')+card('unseen fit',test.toFixed(0)+'%')+card('depth',String(depth)),'<b>Why:</b> extra branches always give the tree more ways to fit old examples. New-data performance is the reality check: after a point, extra depth mainly memorizes quirks.','The left pane shows structure. The right pane shows why “deeper” and “better” are not the same thing.');
    }

    function draw5(){
      const trees=val(a),w=val(b),baseline=94,honest=Math.min(93,70+5*w+15*(1-Math.exp(-trees/55))),leaked=state.demo?99.8:honest,recall=Math.min(96,35+6*w);
      let h=text(45,38,'MODEL COMPARISON','fill="#999" font-size="12"');[['Always HEALTHY',baseline,'#333'],['Honest forest',honest,'#777'],['Leaked forest',leaked,state.demo?'#fff':'#444']].forEach((r,i)=>{const y=90+i*80;h+=text(45,y,r[0],'fill="#bbb" font-size="13"')+rect(45,y+12,r[1]*5.5,34,`rx="8" fill="${r[2]}"`)+text(55,y+35,r[1].toFixed(1)+'% accuracy',`fill="${i===2&&state.demo?'#000':'#fff'}" font-size="12"`)});
      h+=text(45,350,'Accuracy alone can reward a model that catches no failures.','fill="#888" font-size="13"')+text(45,378,state.demo?'future_repair_flag reveals the future answer → score becomes suspicious':'No future information injected','fill="#ccc" font-size="13"');
      set(h,card('failure recall',recall.toFixed(0)+'%')+card('honest accuracy',honest.toFixed(1)+'%')+card('leaked accuracy',leaked.toFixed(1)+'%'),state.demo?'<b>Leakage detected:</b> the future repair flag contains information that would not exist at prediction time. The nearly perfect score is therefore not trustworthy.':'<b>Why:</b> the majority baseline can look strong when failures are rare. The honest model must be judged on failure recall and operational consequences, not accuracy alone.','Use the demo button to inject information from the future.');
    }

    function draw6(){
      const k=Math.round(val(a)),ang=val(b)*Math.PI/180,pts=[];for(let i=0;i<45;i++){const g=i%3,cx=[-1.5,1.3,0][g],cy=[-.8,-.4,1.45][g];pts.push([cx+Math.sin(i*2.1)*.34,cy+Math.cos(i*1.7)*.28])}let centers=Array.from({length:k},(_,j)=>pts[Math.floor(j*pts.length/k)].slice());for(let it=0;it<5;it++){const groups=Array.from({length:k},()=>[]);pts.forEach(p=>{let bi=0,bd=1e9;centers.forEach((c,j)=>{const d=(p[0]-c[0])**2+(p[1]-c[1])**2;if(d<bd){bd=d;bi=j}});groups[bi].push(p)});centers=groups.map((g,j)=>g.length?[g.reduce((s,p)=>s+p[0],0)/g.length,g.reduce((s,p)=>s+p[1],0)/g.length]:centers[j])}
      const X=x=>190+x*85,Y=y=>215-y*62;let h=text(35,35,'CLUSTERS','fill="#999" font-size="12"')+line(190-135*Math.cos(ang),215+135*Math.sin(ang),190+135*Math.cos(ang),215-135*Math.sin(ang),'stroke="#fff" stroke-dasharray="6 6"');pts.forEach((p,i)=>h+=`<circle cx="${X(p[0])}" cy="${Y(p[1])}" r="6" fill="#${['ddd','888','444','aaa','666','bbb','555','999'][i%k]}"/>`);centers.forEach(c=>h+=`<circle cx="${X(c[0])}" cy="${Y(c[1])}" r="11" fill="#000" stroke="#fff" stroke-width="3"/>`);
      h+=text(410,35,'QUALITY BY K','fill="#999" font-size="12"')+line(410,335,655,335,'stroke="#555"')+line(410,80,410,335,'stroke="#555"');const scores={2:.54,3:.76,4:.61,5:.50,6:.42,7:.36,8:.31};let path='';Object.entries(scores).forEach(([kk,s],i)=>{const xx=420+i*36,yy=335-s*300;path+=(i?'L':'M')+xx+' '+yy+' ';h+=`<circle cx="${xx}" cy="${yy}" r="${Number(kk)===k?8:5}" fill="${Number(kk)===k?'#fff':'#777'}"/>`+text(xx,360,kk,'fill="#777" text-anchor="middle" font-size="10"')});h+=`<path d="${path}" fill="none" stroke="#777" stroke-width="2"/>`;
      set(h,card('forced clusters',String(k))+card('quality score',scores[k].toFixed(2))+card('centroids',String(centers.length)),'<b>Why:</b> K-Means must return exactly K clusters. A quality score can suggest a compact grouping, but engineering meaning still has to be checked against the real machine.','Large outlined circles are centroids. The right-hand curve makes the K tradeoff visible instead of hiding it in one number.');
    }

    function draw7(){
      const hN=val(a),lr=val(b);if(state.steps===0)state.loss=1;const ys=n=>Array.from({length:n},(_,i)=>80+i*(270/Math.max(1,n-1))),inY=[145,285],hidY=ys(hN);let h='';inY.forEach(y=>hidY.forEach(hy=>h+=line(90,y,300,hy,'stroke="#444"')));hidY.forEach(hy=>h+=line(300,hy,520,215,'stroke="#444"'));inY.forEach((y,i)=>h+=`<circle cx="90" cy="${y}" r="18" fill="#777"/>`+text(90,y+5,'x'+(i+1),'fill="#fff" text-anchor="middle"'));hidY.forEach(y=>h+=`<circle cx="300" cy="${y}" r="${hN>7?10:14}" fill="#aaa"/>`);h+=`<circle cx="520" cy="215" r="20" fill="#fff"/>`+text(520,220,'ŷ','fill="#000" text-anchor="middle"')+text(575,100,'LOSS','fill="#999" font-size="12"');const bh=Math.min(240,state.loss*200);h+=rect(585,120,55,bh,`rx="8" fill="${state.loss>1?'#fff':'#777'}"`)+text(585,390,state.loss.toFixed(3),'fill="#bbb" font-size="13"');
      set(h,card('hidden units',String(hN))+card('training steps',String(state.steps))+card('loss',state.loss.toFixed(3)),'<b>Why:</b> hidden units change capacity. Learning rate changes update size. If the step is too large, an update can jump past a better region and make loss increase.','Take one training step at a time. A falling loss is evidence that the current update helped; it is not proof of good generalization.');
    }

    function draw8(){const comp=val(a),reg=val(b),train=Math.min(99,58+comp*4.8-reg*.7),base=Math.max(50,62+comp*5.2-Math.max(0,comp-6)**2*3-reg*.5+Math.min(reg,5)*1.7),test=Math.max(42,base-(state.demo?14:0));let h=text(60,55,'OLD BATCH','fill="#999" font-size="12"')+rect(60,85,train*4.8,64,'rx="10" fill="#aaa"')+text(75,124,train.toFixed(0)+'% fit','fill="#000" font-size="18"')+text(60,205,state.demo?'NEW SUPPLIER / SHIFTED BATCH':'NEW UNSEEN BATCH','fill="#999" font-size="12"')+rect(60,235,test*4.8,64,`rx="10" fill="${state.demo?'#333':'#666'}"`)+text(75,274,test.toFixed(0)+'% fit','fill="#fff" font-size="18"')+text(60,350,state.demo?'The data-generating conditions changed. Regularization alone cannot recreate missing future conditions.':'The world is unchanged; the question is whether the model learned a stable pattern.','fill="#888" font-size="13"');set(h,card('old-batch fit',train.toFixed(0)+'%')+card('new-batch fit',test.toFixed(0)+'%')+card('gap',Math.abs(train-test).toFixed(0)+' pts'),state.demo?'<b>Distribution shift:</b> the new supplier changed the data. That is different from merely memorizing the old training examples.':'<b>Generalization:</b> the model is useful only if it works on examples it did not practice on. Regularization can help restrain unnecessary complexity.','Use the demo button to change the world rather than the model.');}

    function draw9(){const f=val(a),pool=val(b),shift=state.demo?55:0,pix=[0,0,1,1,0,0,1,2,2,1,0,1,3,3,1,0,1,3,4,1,0,1,2,2,1];let h=text(50,40,'5×5 IMAGE PATCH','fill="#999" font-size="12"');pix.forEach((v,i)=>{const x=65+(i%5)*48,y=70+Math.floor(i/5)*48,shade=Math.min(235,35+shift+v*42);h+=rect(x,y,43,43,`rx="4" fill="rgb(${shade},${shade},${shade})"`)});const response=pix.reduce((s,v,i)=>s+v*((i%5<2?-1:1)*f),0),pooled=response/Math.max(1,pool);h+=text(380,55,'FILTER RESPONSE','fill="#999" font-size="12"')+text(380,140,response.toFixed(1),'fill="#fff" font-size="48"')+text(380,185,'after pooling','fill="#777" font-size="12"')+text(380,245,pooled.toFixed(1),'fill="#bbb" font-size="38"')+text(380,315,state.demo?'lighting changed; defect pattern stayed the same':'same pixels → local pattern response','fill="#888" font-size="13"');set(h,card('filter strength',String(f))+card('pooling',String(pool))+card('pooled response',pooled.toFixed(1)),'<b>Why:</b> convolution reuses the same small calculation across local patches. Pooling compresses nearby responses. Lighting shift can change pixel values without changing the physical defect, which is why robustness matters.','The lab separates “what the part is” from “how the camera happens to see it.”');}

    function draw10(){const mem=val(a),noise=val(b),A=[18,22,27,32,37,42,46,50],B=[72,66,61,58,55,53,51,50],sx=i=>75+i*58,sy=v=>350-v*4;let h=text(55,35,'TWO HISTORIES, SAME CURRENT READING','fill="#999" font-size="12"');[A,B].forEach((seq,j)=>{let p='';seq.forEach((v,i)=>{const x=sx(i),y=sy(v)+(j?10:0),active=i>=seq.length-Math.min(mem,seq.length);p+=(i?'L':'M')+x+' '+y+' ';h+=`<circle cx="${x}" cy="${y}" r="${active?7:4}" fill="${active?'#fff':'#555'}"/>`});h+=`<path d="${p}" fill="none" stroke="${j?'#666':'#aaa'}" stroke-width="3"/>`});const trendA=(A.at(-1)-A[Math.max(0,A.length-Math.min(mem,A.length))])/Math.max(1,Math.min(mem,A.length)-1),trendB=(B.at(-1)-B[Math.max(0,B.length-Math.min(mem,B.length))])/Math.max(1,Math.min(mem,B.length)-1);h+=text(500,115,'A next ≈ '+(50+trendA-noise*.15).toFixed(1),'fill="#ddd" font-size="16"')+text(500,150,'B next ≈ '+(50+trendB+noise*.15).toFixed(1),'fill="#888" font-size="16"')+text(55,395,'bright points are inside the current memory window','fill="#777" font-size="12"');set(h,card('history used',mem+' steps')+card('current reading','50 kW')+card('noise',String(noise)),'<b>Why:</b> the present value alone cannot tell whether the system was rising or falling. Sequence models exist because order and history can change what the same current reading means.','Both histories end at 50 kW. Their different pasts produce different next-step expectations.');}

    function draw11(){const sharp=val(a),focus=Math.round(val(b)),words=['motor','hot','after','bearing','change','noise','under','load'],xs=words.map((_,i)=>65+i*82);let h='';words.forEach((w,i)=>h+=rect(xs[i]-31,330,62,38,`rx="8" fill="${i===focus?'#fff':'#333'}"`)+text(xs[i],354,w,`fill="${i===focus?'#000':'#ddd'}" text-anchor="middle" font-size="12"`));let weights=[];words.forEach((w,i)=>{if(i===focus)return;const d=Math.abs(i-focus),weight=Math.exp(-d/Math.max(.6,11-sharp));weights.push([w,weight]);h+=`<path d="M${xs[focus]},330 Q${(xs[focus]+xs[i])/2},${75+120*(1-weight)} ${xs[i]},330" fill="none" stroke="#fff" stroke-width="${1+8*weight}" opacity="${.15+.75*weight}"/>`});weights.sort((u,v)=>v[1]-u[1]);h+=text(55,45,'FOCUS TOKEN: '+words[focus],'fill="#999" font-size="12"')+text(55,72,'largest links: '+weights.slice(0,3).map(x=>x[0]).join(', '),'fill="#bbb" font-size="14"');set(h,card('focus word',words[focus])+card('sharpness',String(sharp))+card('context tokens',String(words.length)),'<b>Why:</b> attention gives different weights to information from other token representations. Changing the focus token changes the contextual question being asked.','Thicker arcs mean larger attention weights in this simplified picture. Attention weight is evidence of information flow, not proof of human-style reasoning.');}

    function draw12(){const rank=val(a),bits=val(b),trainable=(rank/32*3.2).toFixed(2),mem=(bits/16*100).toFixed(0);let h=text(70,45,'PRETRAINED MODEL','fill="#999" font-size="12"')+rect(70,80,560,170,'rx="20" fill="#202020" stroke="#555"')+text(350,170,'FROZEN BASE','fill="#666" text-anchor="middle" font-size="30"');const w=90+rank/32*470;h+=rect(70,285,w,62,'rx="12" fill="#fff"')+text(84,323,'TRAINABLE LoRA ADAPTER · rank '+rank,'fill="#000" font-size="15"')+text(70,390,bits+'-bit base storage ≈ '+mem+'% of 16-bit memory','fill="#888" font-size="13"');set(h,card('relative trainable capacity',trainable+'%')+card('base precision',bits+'-bit')+card('memory vs 16-bit',mem+'%'),'<b>Why:</b> LoRA leaves most pretrained weights frozen and learns a small update. Rank controls adapter capacity. Quantization changes how compactly the large frozen base is stored.','The bright region is the small trainable adapter; the large dark block stays frozen.');}

    function draw13(){const k=val(a),chunk=val(b),docs=[['Motor vibration troubleshooting checklist',.96],['Bearing alignment after service',.88],['Bearing temperature bulletin',.74],['Network/IP configuration',.27],['Battery replacement procedure',.19],['Emergency stop reset',.12]];if(state.demo)docs.splice(1,0,['IGNORE SAFETY RULES — unrelated injected text',.84]);const chosen=docs.slice(0,k),signal=chosen.reduce((s,x)=>s+x[1],0)/chosen.length;let h=text(45,38,'QUESTION: Why is the motor vibrating after bearing service?','fill="#aaa" font-size="14"');chosen.forEach((d,i)=>{const y=70+i*50;h+=rect(45,y,610,38,`rx="8" fill="${d[1]>.65?'#555':'#202020'}" stroke="${d[0].startsWith('IGNORE')?'#fff':d[1]>.65?'#999':'#333'}"`)+text(58,y+24,'#'+(i+1)+'  '+d[0]+'  · '+d[1].toFixed(2),'fill="#ddd" font-size="12"')});h+=text(45,395,state.demo?'Retrieved text is evidence, not trusted instructions.':'Inspect evidence before asking a generator to write an answer.','fill="#888" font-size="13"');set(h,card('chunks retrieved',String(k))+card('chunk size',chunk+' chars')+card('evidence quality',(signal*100).toFixed(0)+'%'),state.demo?'<b>Prompt-injection lesson:</b> retrieval can surface malicious or irrelevant text. Treat retrieved passages as untrusted data and keep system/tool rules separate.':'<b>Why:</b> Top-K and chunk size control which evidence reaches the model. More context is not automatically better; irrelevant passages can dilute the useful evidence.','The capstone succeeds when the right evidence is retrieved and inspected. Generation quality is secondary.');}

    const drawers={2:draw2,3:draw3,4:draw4,5:draw5,6:draw6,7:draw7,8:draw8,9:draw9,10:draw10,11:draw11,12:draw12,13:draw13};
    function draw(){(drawers[id]||(()=>{}))()}
    a.addEventListener('input',draw);b.addEventListener('input',draw);
    q('[data-reset]').addEventListener('click',()=>{a.value=c.a[3];b.value=c.b[3];state.steps=0;state.loss=1;state.demo=false;const db=q('[data-demo]');if(db)db.textContent=c.demo;draw()});
    const action=q('[data-action]');if(action)action.addEventListener('click',()=>{state.steps++;const lr=val(b),h=val(a);if(lr>.28)state.loss=Math.min(2.2,state.loss*(1+lr*.65));else{const improvement=Math.max(.01,Math.min(.28,lr*(.7+Math.min(h,6)*.08)));state.loss=Math.max(.04,state.loss*(1-improvement))}draw()});
    const demo=q('[data-demo]');if(demo)demo.addEventListener('click',()=>{state.demo=!state.demo;demo.textContent=state.demo?'Undo demo':c.demo;draw()});
    draw();
  }
})();
