/* ModelQuest v10 — self-contained TRY IT labs for Models 2–13. */
(()=>{
  const CFG={
    2:{title:'Quality Gate · Threshold Lab',a:['Decision threshold',0.05,0.95,0.50,0.05],b:['Cost of missing a defect',1,10,6,1],mission:'Move the cutoff and watch which parts switch between PASS and FAIL. Notice that the model scores stay fixed while the decision rule changes.'},
    3:{title:'Machine State · KNN Geometry Lab',a:['Neighbors (K)',1,9,3,2],b:['Temperature scale',1,10,1,1],mission:'Change K and the numerical scale of temperature. Watch which stored machine states count as “nearest.”'},
    4:{title:'Late Shipment · Tree Depth Lab',a:['Maximum depth',1,10,3,1],b:['Minimum samples per leaf',1,20,5,1],mission:'Grow the tree and compare training fit with unseen-data performance. More branches can eventually become memorization.'},
    5:{title:'Predictive Maintenance · Forest Lab',a:['Number of trees',5,200,50,5],b:['Failure importance',1,10,5,1],mission:'Add more trees and change how strongly rare failures matter. Then deliberately inject future information and see why a perfect score can be bad news.',demo:'Inject future_repair_flag'},
    6:{title:'Hidden Modes · K-Means + PCA Lab',a:['Clusters (K)',2,8,3,1],b:['PCA view angle',0,90,25,5],mission:'Force different numbers of clusters, including K=8, then rotate the lower-dimensional view. A mathematical grouping is not automatically a real machine mode.'},
    7:{title:'Sensor Fusion · Neural Network Lab',a:['Hidden neurons',1,10,4,1],b:['Learning rate',0.01,0.50,0.12,0.01],mission:'Change network capacity and learning rate, then take training steps. Watch structure and loss change together. A very large step can make loss worse.',action:'Train one step'},
    8:{title:'New-Batch Test · Generalization Lab',a:['Model complexity',1,10,5,1],b:['Regularization strength',0,10,3,1],mission:'Increase model complexity and regularization. Compare old-batch fit with new-batch performance rather than chasing training score.'},
    9:{title:'Surface Defect Vision · CNN Filter Lab',a:['Edge filter strength',-2,2,1,1],b:['Pooling size',1,4,2,1],mission:'Change a small image filter and pooling size. Watch how the same local pixels produce a different feature response.'},
    10:{title:'Energy Forecast · Memory Lab',a:['History length',1,12,5,1],b:['Signal noise',0,10,2,1],mission:'Change how much past information is available. The same current reading can imply different futures when its history is different.'},
    11:{title:'Maintenance Notes · Attention Lab',a:['Attention sharpness',1,10,5,1],b:['Focus token',0,7,4,1],mission:'Select a token and change attention sharpness. Watch which surrounding words contribute most strongly to its context.'},
    12:{title:'Technician Report Adapter · LoRA Lab',a:['LoRA rank',1,32,8,1],b:['Quantization bits',4,16,8,4],mission:'Increase adapter rank and change weight precision. Watch trainable capacity and approximate memory move in opposite directions.'},
    13:{title:'Engineering Copilot · RAG Lab',a:['Top-K chunks',1,6,3,1],b:['Chunk size',100,800,350,50],mission:'Retrieve more document chunks and change chunk size. More context can help until irrelevant evidence starts crowding the answer.'}
  };

  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function shell(id){
    const c=CFG[id];
    if(!c)return '<div class="mq10-error">No interactive lab is defined for this model yet.</div>';
    const range=(key,x)=>`<label class="mq10-control"><span>${esc(x[0])} <b data-out="${key}">${x[3]}</b></span><input data-control="${key}" type="range" min="${x[1]}" max="${x[2]}" value="${x[3]}" step="${x[4]}"></label>`;
    return `<div class="mq10-lab" id="mq10Lab" data-model="${id}">
      <div class="mq10-head"><div><small>LIVE TRY IT LAB</small><h2>${esc(c.title)}</h2><p>${esc(c.mission)}</p></div><div class="mq10-rule">Predict → change one thing → observe → explain why</div></div>
      <div class="mq10-grid"><div class="mq10-stage"><svg data-viz viewBox="0 0 700 430" role="img"></svg><div class="mq10-caption" data-caption></div></div>
      <aside class="mq10-controls">${range('a',c.a)}${range('b',c.b)}${c.action?`<button type="button" class="mq10-action" data-action>${esc(c.action)}</button>`:''}${c.demo?`<button type="button" class="mq10-action" data-demo>${esc(c.demo)}</button>`:''}<button type="button" class="mq10-reset" data-reset>Reset lab</button><div class="mq10-metrics" data-metrics></div><div class="mq10-explain" data-explain></div></aside></div>
    </div>`;
  }

  window.mqLabFor=id=>shell(Number(id));
  window.mqInitLab=id=>init(Number(id));

  function init(id){
    const root=document.querySelector('#mq10Lab');
    if(!root||Number(root.dataset.model)!==id)return;
    const c=CFG[id];
    const qa=s=>root.querySelector(s);
    const a=qa('[data-control="a"]'),b=qa('[data-control="b"]');
    const state={steps:0,loss:1.0,demo:false};
    function val(el){return Number(el.value)}
    function line(x1,y1,x2,y2,extra=''){return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" ${extra}/>`}
    function text(x,y,t,extra=''){return `<text x="${x}" y="${y}" ${extra}>${esc(t)}</text>`}
    function set(html,metrics,explain,caption){qa('[data-viz]').innerHTML=html;qa('[data-metrics]').innerHTML=metrics;qa('[data-explain]').innerHTML=explain;qa('[data-caption]').innerHTML=caption||'';qa('[data-out="a"]').textContent=fmt(val(a));qa('[data-out="b"]').textContent=fmt(val(b));}
    function fmt(v){return Number.isInteger(v)?String(v):v.toFixed(2)}
    function card(k,v){return `<div><small>${esc(k)}</small><b>${esc(v)}</b></div>`}

    function draw2(){const t=val(a),cost=val(b);const rows=[['PASS',.12],['PASS',.24],['FAIL',.31],['PASS',.41],['FAIL',.48],['PASS',.54],['FAIL',.58],['PASS',.63],['FAIL',.72],['FAIL',.82],['FAIL',.91]];let tp=0,tn=0,fp=0,fn=0;const x=s=>65+s*565;let dots='';rows.forEach(([actual,s],i)=>{const fail=s>=t,real=actual==='FAIL';if(fail&&real)tp++;else if(fail&&!real)fp++;else if(!fail&&real)fn++;else tn++;dots+=`<circle cx="${x(s)}" cy="${120+(i%4)*55}" r="11" fill="${real?'#fff':'#666'}" stroke="${fail?'#fff':'#222'}" stroke-width="4"><title>${actual} · score ${s}</title></circle>`});const recall=tp/(tp+fn||1),precision=tp/(tp+fp||1),weighted=fn*cost+fp;set(`${line(65,345,630,345,'stroke="#555"')}${line(x(t),55,x(t),355,'stroke="#fff" stroke-width="4" stroke-dasharray="8 8"')}${dots}${text(65,395,'lower FAIL score → higher FAIL score','fill="#888"')}${text(Math.min(555,x(t)+10),75,'threshold '+t.toFixed(2),'fill="#fff"')}`,card('defects caught',(recall*100).toFixed(0)+'%')+card('alarm precision',(precision*100).toFixed(0)+'%')+card('weighted mistake cost',String(weighted)),`<b>Why it changes:</b> lowering the threshold labels more parts as FAIL. That usually catches more real defects, but it can also reject more good parts. The defect-cost slider does not change the scores; it changes how painful a miss is.`,`White-filled dots are actual defects. A white outline means the current threshold predicts FAIL.`)}

    function draw3(){const k=Math.round(val(a)),scale=val(b);const pts=[[-1.8,-.8,'NORMAL'],[-1.2,.1,'NORMAL'],[-.7,-.5,'NORMAL'],[.8,.7,'UNBALANCED'],[1.2,.2,'UNBALANCED'],[1.7,.9,'UNBALANCED'],[-.2,1.7,'OVERLOAD'],[.3,1.4,'OVERLOAD'],[-.5,1.1,'OVERLOAD']];const q=[.1,.45];const dist=pts.map((p,i)=>({i,d:Math.hypot(p[0]-q[0],(p[1]-q[1])*scale),p})).sort((x,y)=>x.d-y.d);const near=dist.slice(0,k);const votes={};near.forEach(x=>votes[x.p[2]]=(votes[x.p[2]]||0)+1);const winner=Object.entries(votes).sort((x,y)=>y[1]-x[1])[0]?.[0]||'?';const X=x=>350+x*120,Y=y=>230-y*85;let html=line(70,230,630,230,'stroke="#333"')+line(350,45,350,385,'stroke="#333"');pts.forEach((p,i)=>{const chosen=near.some(n=>n.i===i);if(chosen)html+=line(X(q[0]),Y(q[1]),X(p[0]),Y(p[1]),'stroke="#888" stroke-dasharray="5 6"');html+=`<circle cx="${X(p[0])}" cy="${Y(p[1])}" r="10" fill="${p[2]==='NORMAL'?'#ddd':p[2]==='UNBALANCED'?'#888':'#444'}" stroke="${chosen?'#fff':'#222'}" stroke-width="3"/>`});html+=`<circle cx="${X(q[0])}" cy="${Y(q[1])}" r="13" fill="#fff" stroke="#000" stroke-width="4"/>`+text(74,410,'vibration →','fill="#888"')+text(370,58,'temperature influence ↑','fill="#888"');set(html,card('prediction',winner)+card('K',String(k))+card('temp scale',scale.toFixed(0)+'×'),`<b>Why it changes:</b> K controls how many neighbors vote. Temperature scale changes the geometry used by distance, so it can change which examples are considered close even though the physical machine did not change.`,`The white point is the unknown reading. Outlined stored points are the current K nearest neighbors.`)}

    function draw4(){const depth=val(a),leaf=val(b);const train=Math.min(99,58+depth*5.2);const test=Math.max(52,58+depth*7-Math.max(0,depth-5)**2*2.2-leaf*.35);let html=text(70,55,'Decision tree grows by asking more questions','fill="#aaa" font-size="18"');const levels=Math.min(4,depth);for(let d=0;d<levels;d++){const n=2**d;for(let i=0;i<n;i++){const x=(i+.5)*700/n,y=105+d*78;html+=`<rect x="${x-42}" y="${y-19}" width="84" height="38" rx="9" fill="none" stroke="#${d<2?'fff':'666'}"/>`+text(x,y+5,d===0?'queue?':d===1?'distance?':'condition?','fill="#bbb" text-anchor="middle" font-size="12"');if(d<levels-1){html+=line(x,y+19,(i*2+.5)*700/(n*2),y+59,'stroke="#555"')+line(x,y+19,(i*2+1.5)*700/(n*2),y+59,'stroke="#555"')}}}set(html,card('training fit',train.toFixed(0)+'%')+card('unseen fit',test.toFixed(0)+'%')+card('tree depth',String(depth)),`<b>Why it changes:</b> deeper trees can describe more specific rules, so training fit keeps rising. After a point those extra branches mainly memorize quirks and unseen performance falls. Larger leaf requirements restrain tiny branches.`,`Only the first few levels are drawn; the metric shows the effect of the full selected depth.`)}

    function draw5(){const trees=val(a),w=val(b);const stability=Math.min(97,55+40*(1-Math.exp(-trees/50)));const recall=Math.min(98,50+4.5*w);let html=text(70,50,state.demo?'LEAKED FUTURE FEATURE ADDED':'Each column is one tree vote',`fill="${state.demo?'#fff':'#aaa'}" font-size="18"`);for(let i=0;i<Math.min(40,Math.ceil(trees/5));i++){const x=75+(i%10)*55,y=90+Math.floor(i/10)*70;html+=`<rect x="${x}" y="${y}" width="32" height="42" rx="7" fill="${state.demo?'#ddd':i%4===0?'#555':'#aaa'}" opacity="${state.demo?.95:.45+(i%5)*.1}"/>`}html+=text(70,390,state.demo?'Perfect-looking validation can be a warning sign when the answer leaked into the features.':'Different trees see different samples/features; the forest combines their votes.','fill="#888" font-size="14"');if(state.demo){set(html,card('validation accuracy','100%')+card('failure recall','100%')+card('trust','BROKEN'),`<b>What happened:</b> future_repair_flag reveals the outcome. The forest did not become smarter; the evaluation became dishonest. Remove the feature before doing anything else.`,`This is an intentional leakage demonstration. A suspiciously perfect score is the failure, not the success.`)}else{set(html,card('vote stability',stability.toFixed(0)+'%')+card('failure recall',recall.toFixed(0)+'%')+card('trees',String(trees)),`<b>Why it changes:</b> more diverse trees usually stabilize the combined vote, but gains flatten. Failure importance changes the cost of missing rare failures, which pushes the model toward catching more of them.`,`More trees help only when they are not identical copies of one another.`)}}

    function draw6(){const k=val(a),ang=val(b)*Math.PI/180;const pts=[];for(let i=0;i<36;i++){const g=i%3,cx=[-1.5,1.3,0][g],cy=[-.8,-.4,1.45][g];pts.push([cx+Math.sin(i*2.1)*.35,cy+Math.cos(i*1.7)*.3])}let centers=Array.from({length:k},(_,j)=>pts[Math.floor(j*pts.length/k)].slice());for(let iter=0;iter<5;iter++){const groups=Array.from({length:k},()=>[]);pts.forEach(p=>{let bi=0,bd=1e9;centers.forEach((c,j)=>{const d=(p[0]-c[0])**2+(p[1]-c[1])**2;if(d<bd){bd=d;bi=j}});groups[bi].push(p)});centers=groups.map((g,j)=>g.length?[g.reduce((s,p)=>s+p[0],0)/g.length,g.reduce((s,p)=>s+p[1],0)/g.length]:centers[j])}const shades=['ddd','c4c4c4','aaa','909090','777','606060','4b4b4b','383838'];const X=x=>350+x*120,Y=y=>220-y*90;let html=line(350-270*Math.cos(ang),220+270*Math.sin(ang),350+270*Math.cos(ang),220-270*Math.sin(ang),'stroke="#fff" stroke-dasharray="8 8"');pts.forEach((p,i)=>html+=`<circle cx="${X(p[0])}" cy="${Y(p[1])}" r="7" fill="#${shades[i%k]}"/>`);centers.forEach(c=>html+=`<circle cx="${X(c[0])}" cy="${Y(c[1])}" r="13" fill="#000" stroke="#fff" stroke-width="4"/>`);set(html,card('forced clusters',String(k))+card('projection angle',val(b).toFixed(0)+'°')+card('centroids',String(centers.length)),`<b>Why it changes:</b> K-Means must return exactly K groups, including eight if you ask for eight, even when that does not match the real structure. The rotating PCA-style axis changes only the view of variation.`,`Large outlined circles are centroids. The dashed line is the current lower-dimensional projection direction.`)}

    function draw7(){const h=val(a),lr=val(b);if(state.steps===0)state.loss=1.0;const ys=n=>Array.from({length:n},(_,i)=>80+i*(270/Math.max(1,n-1)));const inY=[145,285],hidY=ys(h);let html='';inY.forEach(y=>hidY.forEach(hy=>html+=line(110,y,350,hy,'stroke="#444"')));hidY.forEach(hy=>html+=line(350,hy,590,215,'stroke="#444"'));inY.forEach((y,i)=>html+=`<circle cx="110" cy="${y}" r="20" fill="#777"/>`+text(110,y+5,'x'+(i+1),'fill="#fff" text-anchor="middle"'));hidY.forEach(y=>html+=`<circle cx="350" cy="${y}" r="${h>7?11:16}" fill="#aaa"/>`);html+=`<circle cx="590" cy="215" r="22" fill="#fff"/>`+text(590,220,'ŷ','fill="#000" text-anchor="middle"');const stateName=lr>.28?'TOO LARGE':lr<.04?'VERY SMALL':'USEFUL RANGE';set(html,card('hidden units',String(h))+card('training steps',String(state.steps))+card('loss',state.loss.toFixed(3))+card('step-size zone',stateName),`<b>Why it changes:</b> hidden neurons add capacity. Learning rate controls update size. Small steps move slowly; a useful range reduces loss; a very large step can jump past a better region and make loss grow.`,`Use “Train one step” repeatedly. With learning rate above about 0.28 in this teaching simulation, watch loss move the wrong way.`)}

    function draw8(){const comp=val(a),reg=val(b);const train=Math.min(99,58+comp*4.8-reg*.7);const test=Math.max(50,62+comp*5.2-Math.max(0,comp-6)**2*3-reg*.5+Math.min(reg,5)*1.7);let html=text(80,65,'Old batch vs new batch','fill="#aaa" font-size="20"');html+=`<rect x="90" y="120" width="${train*4.7}" height="70" rx="12" fill="#aaa"/>${text(100,164,'training '+train.toFixed(0)+'%','fill="#000" font-size="18"')}<rect x="90" y="245" width="${test*4.7}" height="70" rx="12" fill="#555"/>${text(100,289,'new batch '+test.toFixed(0)+'%','fill="#fff" font-size="18"')}`;set(html,card('old-batch fit',train.toFixed(0)+'%')+card('new-batch fit',test.toFixed(0)+'%')+card('gap',Math.abs(train-test).toFixed(0)+' pts'),`<b>Why it changes:</b> complexity can keep improving performance on familiar data after it stops helping new data. Regularization deliberately limits extreme fitting so the learned rule has a better chance of surviving outside training.`,`The goal is not the longest top bar. The goal is reliable performance on data the model did not practice on.`)}

    function draw9(){const f=val(a),pool=val(b);const pix=[0,0,1,1,0,0,1,2,2,1,0,1,3,3,1,0,1,3,4,1,0,1,2,2,1];let html=text(70,45,'5×5 image patch','fill="#aaa" font-size="18"');pix.forEach((v,i)=>{const x=90+(i%5)*58,y=80+Math.floor(i/5)*58,shade=40+v*45;html+=`<rect x="${x}" y="${y}" width="52" height="52" rx="5" fill="rgb(${shade},${shade},${shade})"/>`});const response=pix.reduce((s,v,i)=>s+v*((i%5<2?-1:1)*f),0)/Math.max(1,pool);html+=text(430,130,'feature response','fill="#aaa" font-size="16"')+text(430,210,response.toFixed(1),'fill="#fff" font-size="58"')+text(430,260,'pool '+pool+'×','fill="#888" font-size="18"');set(html,card('filter strength',String(f))+card('pooling',String(pool))+card('response',response.toFixed(1)),`<b>Why it changes:</b> a convolution filter multiplies nearby pixels by a small pattern and adds the result. Changing the filter changes what pattern activates. Pooling summarizes nearby responses and trades detail for compactness.`,`The image itself does not change. The learned representation of that image changes.`)}

    function draw10(){const mem=val(a),noise=val(b);const seq=[18,20,23,27,30,34,37,39,42,45,47,50];let html=line(55,330,650,330,'stroke="#444"');seq.forEach((v,i)=>{const x=70+i*48,y=330-v*4.7;const active=i>=seq.length-mem;html+=line(x,330,x,y,`stroke="${active?'#aaa':'#333'}"`)+`<circle cx="${x}" cy="${y}" r="8" fill="${active?'#fff':'#555'}"/>`});const recent=seq.slice(-mem),trend=(recent[recent.length-1]-recent[0])/Math.max(1,recent.length-1),forecast=seq.at(-1)+trend-noise*.2;html+=text(70,390,'time →','fill="#888"')+text(440,70,'forecast ≈ '+forecast.toFixed(1)+' kW','fill="#fff" font-size="24"');set(html,card('history used',mem+' steps')+card('forecast',forecast.toFixed(1)+' kW')+card('noise',String(noise)),`<b>Why it changes:</b> the current reading alone does not show whether the system was rising, falling, or flat. A longer memory exposes more history, while noise can make old details less useful.`,`Bright points are inside the model’s current history window.`)}

    function draw11(){const sharp=val(a),focus=Math.round(val(b));const words=['motor','hot','after','bearing','change','noise','under','load'];const xs=words.map((_,i)=>70+i*80);let html='';words.forEach((w,i)=>html+=`<rect x="${xs[i]-31}" y="330" width="62" height="38" rx="8" fill="${i===focus?'#fff':'#333'}"/>`+text(xs[i],354,w,`fill="${i===focus?'#000':'#ddd'}" text-anchor="middle" font-size="12"`));words.forEach((w,i)=>{if(i===focus)return;const d=Math.abs(i-focus),weight=Math.exp(-d/Math.max(.6,11-sharp));html+=`<path d="M${xs[focus]},330 Q${(xs[focus]+xs[i])/2},${80+120*(1-weight)} ${xs[i]},330" fill="none" stroke="#fff" stroke-width="${1+8*weight}" opacity="${.15+.75*weight}"/>`});set(html,card('focus word',words[focus])+card('sharpness',String(sharp))+card('context tokens',String(words.length)),`<b>Why it changes:</b> attention gives different relevance weights to surrounding token representations. Sharper attention concentrates more weight on fewer tokens; a different focus token asks a different contextual question.`,`Thicker arcs mean larger attention weights in this simplified visualization, not proof of a human-style explanation.`)}

    function draw12(){const rank=val(a),bits=val(b);const trainable=(rank/32*3.2).toFixed(2);const mem=(bits/16*100).toFixed(0);let html=text(80,60,'Large pretrained model','fill="#aaa" font-size="20"');html+=`<rect x="80" y="100" width="540" height="170" rx="20" fill="#222" stroke="#555"/>`+text(350,190,'FROZEN BASE','fill="#777" text-anchor="middle" font-size="30"');const w=80+rank/32*460;html+=`<rect x="80" y="300" width="${w}" height="60" rx="12" fill="#fff"/>`+text(95,338,'LoRA adapter · rank '+rank,'fill="#000" font-size="18"');set(html,card('adapter capacity',trainable+'% relative')+card('weight precision',bits+'-bit')+card('memory vs 16-bit',mem+'%'),`<b>Why it changes:</b> rank controls how much adaptation capacity the small trainable update has. Fewer bits reduce storage for the frozen base but may introduce compatibility or quality tradeoffs.`,`Most of the model remains frozen; the bright adapter is the small part being trained.`)}

    function draw13(){const k=val(a),chunk=val(b);const docs=[['Motor vibration troubleshooting checklist',.96],['Bearing replacement torque and alignment notes',.88],['Temperature alarm cooling procedure',.63],['Network/IP configuration',.27],['Battery replacement procedure',.19],['Emergency stop reset',.12]];const chosen=docs.slice(0,k);const signal=chosen.reduce((s,x)=>s+x[1],0)/chosen.length;let html=text(55,45,'Question: “Why is the motor vibrating after bearing service?”','fill="#aaa" font-size="17"');chosen.forEach((d,i)=>{const y=80+i*55;html+=`<rect x="55" y="${y}" width="590" height="42" rx="9" fill="${d[1]>.6?'#555':'#222'}" stroke="${d[1]>.6?'#aaa':'#333'}"/>`+text(70,y+26,'#'+(i+1)+'  '+d[0]+'  · relevance '+d[1].toFixed(2),'fill="#ddd" font-size="13"')});set(html,card('chunks retrieved',String(k))+card('chunk size',chunk+' chars')+card('evidence quality',(signal*100).toFixed(0)+'%'),`<b>Why it changes:</b> top-K controls how many passages enter the prompt. Too few can miss evidence; too many can add noise. Chunk size controls how much neighboring context travels with each retrieved match.`,`Darker low-relevance chunks show how extra retrieval can dilute otherwise useful evidence.`)}

    const drawers={2:draw2,3:draw3,4:draw4,5:draw5,6:draw6,7:draw7,8:draw8,9:draw9,10:draw10,11:draw11,12:draw12,13:draw13};
    function draw(){(drawers[id]||(()=>{}))()}
    a.addEventListener('input',draw);b.addEventListener('input',draw);
    qa('[data-reset]').addEventListener('click',()=>{a.value=c.a[3];b.value=c.b[3];state.steps=0;state.loss=1.0;state.demo=false;const demo=qa('[data-demo]');if(demo)demo.textContent=c.demo;draw()});
    const action=qa('[data-action]');if(action)action.addEventListener('click',()=>{state.steps++;const lr=val(b),h=val(a);if(lr>.28){const overshoot=.12+(lr-.28)*.9;state.loss=Math.min(3,state.loss*(1+overshoot));}else{const improvement=Math.max(.008,Math.min(.24,lr*(.65+Math.min(h,6)*.08)));state.loss=Math.max(.04,state.loss*(1-improvement));}draw()});
    const demo=qa('[data-demo]');if(demo)demo.addEventListener('click',()=>{state.demo=!state.demo;demo.textContent=state.demo?'Remove leaked feature':c.demo;draw()});
    draw();
  }
})();
